export const telanganaMBAMCAColleges = [
  {
    name: 'ICFAI Business School Hyderabad',
    shortName: 'IBS Hyderabad', collegeCode: 'IBSH',
    description: 'A premier B-school in Hyderabad known for its management programs. Part of ICFAI group, consistently ranked among top private B-schools in India.',
    establishmentYear: 1995, collegeType: 'MBA/MCA', ownership: 'Private',
    accreditation: 'NAAC A+',
    ranking: { nirf: 75, naacGrade: 'A+' },
    aiScore: { overall: 82, placement: 88, roi: 78, research: 80, infrastructure: 85, studentSatisfaction: 84 },
    campusArea: '30+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Shamshabad', village: 'Shamshabad',
    address: 'IBS Hyderabad, Shankarpally, Shamshabad, Hyderabad, Telangana 501203',
    pinCode: '501203',
    contactEmail: 'admissions@ibsindia.org',
    website: 'https://www.ibsindia.org',
    facilities: ['Library', 'Smart Classrooms', 'Hostels', 'WiFi', 'Sports Complex', 'Auditorium'],
    isVerified: true,
  },
  {
    name: 'University College of Commerce & Business Management OU',
    shortName: 'UCCBM', collegeCode: 'UCCB',
    description: 'The commerce and business school of Osmania University. Offers MBA and other management programs.',
    establishmentYear: 1955, collegeType: 'MBA/MCA', ownership: 'Government',
    accreditation: 'NAAC A++',
    ranking: { naacGrade: 'A++' },
    aiScore: { overall: 78, placement: 76, roi: 82, research: 78, infrastructure: 74, studentSatisfaction: 76 },
    campusArea: '50+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Amberpet', village: 'Adikmet',
    address: 'UCCBM, Osmania University, Amberpet, Hyderabad, Telangana 500007',
    pinCode: '500007',
    website: 'https://www.osmania.ac.in/uccbm.php',
    affiliatedUniversity: 'Osmania University',
    facilities: ['Library', 'Smart Classrooms', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'JNTUH School of Management Studies',
    shortName: 'JSMS', collegeCode: 'JSMS',
    description: 'The management school of JNTUH offering MBA programs with focus on technology management.',
    establishmentYear: 2005, collegeType: 'MBA/MCA', ownership: 'Government',
    accreditation: 'NAAC A+',
    aiScore: { overall: 74, placement: 76, roi: 78, research: 70, infrastructure: 72, studentSatisfaction: 74 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Kukatpally', village: 'Kukatpally',
    address: 'JNTUH School of Management, Kukatpally, Hyderabad, Telangana 500085',
    pinCode: '500085',
    website: 'https://www.jntuh.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Smart Classrooms', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Badruka School of Management',
    shortName: 'BSM', collegeCode: 'BSM',
    description: 'A modern B-school located in Hyderabad offering innovative management programs.',
    establishmentYear: 2019, collegeType: 'MBA/MCA', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 72, placement: 76, roi: 74, research: 68, infrastructure: 80, studentSatisfaction: 76 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Hyderabad',
    address: 'Badruka School of Management, Hyderabad, Telangana 500001',
    pinCode: '500001',
    website: 'https://www.badruka.edu.in',
    facilities: ['Library', 'Smart Classrooms', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Aurora Business School',
    shortName: 'ABS', collegeCode: 'ABS',
    description: 'A B-school offering MBA programs under Aurora group, located in Hyderabad.',
    establishmentYear: 2005, collegeType: 'MBA/MCA', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 68, placement: 72, roi: 72, research: 62, infrastructure: 72, studentSatisfaction: 70 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Hyderabad',
    address: 'Aurora Business School, Hyderabad, Telangana 500001',
    pinCode: '500001',
    website: 'https://www.aurorabschool.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Smart Classrooms', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'St. Mary\'s Group of Institutions (MBA)',
    shortName: 'SMGI', collegeCode: 'SMGI',
    description: 'Offers MBA programs under St. Mary\'s group in Hyderabad.',
    establishmentYear: 2005, collegeType: 'MBA/MCA', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 66, placement: 70, roi: 70, research: 60, infrastructure: 70, studentSatisfaction: 68 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Hyderabad',
    address: 'St. Mary\'s Group, Hyderabad, Telangana 500001',
    pinCode: '500001',
    website: 'https://www.stmarysgroup.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Smart Classrooms', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Malla Reddy Institute of Management',
    shortName: 'MRIM', collegeCode: 'MRIM',
    description: 'A management institute under Malla Reddy group offering MBA programs.',
    establishmentYear: 2005, collegeType: 'MBA/MCA', ownership: 'Private',
    accreditation: 'NAAC B++',
    aiScore: { overall: 64, placement: 68, roi: 70, research: 58, infrastructure: 68, studentSatisfaction: 66 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Maisammaguda', village: 'Dulapally',
    address: 'MRIM, Maisammaguda, Hyderabad, Telangana 500100',
    pinCode: '500100',
    website: 'https://www.mrim.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Smart Classrooms', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'CBIT MBA Department',
    shortName: 'CBIT MBA', collegeCode: 'CBIM',
    description: 'MBA program offered at Chaitanya Bharathi Institute of Technology, one of the top engineering colleges in Hyderabad.',
    establishmentYear: 2000, collegeType: 'MBA/MCA', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    aiScore: { overall: 76, placement: 80, roi: 76, research: 72, infrastructure: 78, studentSatisfaction: 78 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Gandipet', village: 'Gandipet',
    address: 'CBIT, Gandipet, Hyderabad, Telangana 500075',
    pinCode: '500075',
    website: 'https://www.cbit.ac.in',
    affiliatedUniversity: 'Osmania University',
    facilities: ['Library', 'Smart Classrooms', 'WiFi', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'VNR VJIET MBA Department',
    shortName: 'VNR MBA', collegeCode: 'VNRM',
    description: 'MBA program at VNR Vignana Jyothi Institute of Engineering & Technology.',
    establishmentYear: 2000, collegeType: 'MBA/MCA', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    aiScore: { overall: 75, placement: 78, roi: 75, research: 70, infrastructure: 78, studentSatisfaction: 76 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Bachupally', village: 'Bachupally',
    address: 'VNR VJIET, Bachupally, Hyderabad, Telangana 500090',
    pinCode: '500090',
    website: 'https://www.vnrvjiet.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Smart Classrooms', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Vardhaman College MBA Department',
    shortName: 'Vardhaman MBA', collegeCode: 'VARD',
    description: 'MBA program at Vardhaman College of Engineering.',
    establishmentYear: 2005, collegeType: 'MBA/MCA', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    aiScore: { overall: 74, placement: 78, roi: 74, research: 68, infrastructure: 76, studentSatisfaction: 75 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Shamshabad', village: 'Kacharam',
    address: 'Vardhaman College, Shamshabad, Hyderabad, Telangana 501218',
    pinCode: '501218',
    website: 'https://www.vardhaman.org',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Smart Classrooms', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'MGIT MCA Department',
    shortName: 'MGIT MCA', collegeCode: 'MGIM',
    description: 'MCA program at Mahatma Gandhi Institute of Technology.',
    establishmentYear: 2000, collegeType: 'MBA/MCA', ownership: 'Autonomous',
    accreditation: 'NAAC A',
    aiScore: { overall: 72, placement: 74, roi: 74, research: 66, infrastructure: 74, studentSatisfaction: 73 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Kisara', village: 'Kisara',
    address: 'MGIT, Kisara, Hyderabad, Telangana 500039',
    pinCode: '500039',
    website: 'https://www.mgit.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'MJCET MBA Department',
    shortName: 'MJCET MBA', collegeCode: 'MJCM',
    description: 'MBA program at Muffakham Jah College of Engineering & Technology.',
    establishmentYear: 2005, collegeType: 'MBA/MCA', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 70, placement: 72, roi: 72, research: 66, infrastructure: 72, studentSatisfaction: 70 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Banjara Hills', village: 'Banjara Hills',
    address: 'MJCET, Banjara Hills, Hyderabad, Telangana 500034',
    pinCode: '500034',
    website: 'https://www.mjcollege.ac.in',
    affiliatedUniversity: 'Osmania University',
    facilities: ['Library', 'Smart Classrooms', 'WiFi'],
    isVerified: true,
  },
];

