export const telanganaUniversities = [
  {
    name: 'Osmania University',
    shortName: 'OU',
    collegeCode: 'OU',
    description: 'One of the oldest and largest universities in India, offering diverse programs across engineering, arts, sciences, law, and management. Founded in 1918, it is a NAAC A++ accredited state university with a sprawling 1600+ acre campus in the heart of Hyderabad.',
    establishmentYear: 1918,
    collegeType: 'University',
    ownership: 'State University',
    accreditation: 'NAAC A++',
    ranking: { nirf: 18, qs: 1001, naacGrade: 'A++', nbaAccreditation: true },
    aiScore: { overall: 88, placement: 78, roi: 85, research: 92, infrastructure: 80, studentSatisfaction: 82 },
    campusArea: '1600+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Amberpet', village: 'Adikmet',
    address: 'Osmania University Main Road, Amberpet, Hyderabad, Telangana 500007',
    pinCode: '500007',
    googleMapsCoordinates: { lat: 17.4065, lng: 78.5189 },
    googleMapsUrl: 'https://maps.google.com/?q=Osmania+University+Hyderabad',
    contactEmail: 'info@osmania.ac.in', contactPhone: '040-27682222',
    admissionCell: '040-27682300',
    website: 'https://www.osmania.ac.in',
    socialLinks: { facebook: 'https://facebook.com/osmaniauniversity', twitter: 'https://twitter.com/osmaniauni', linkedin: 'https://linkedin.com/school/osmania-university' },
    isoCertification: 'ISO 9001:2015',
    facilities: ['Central Library', 'Advanced Research Labs', 'Sports Stadium', 'WiFi Campus', 'Medical Center', 'Auditorium', 'Hostels', 'Bank', 'Post Office', 'Guest House'],
    isVerified: true,
  },
  {
    name: 'Jawaharlal Nehru Technological University Hyderabad',
    shortName: 'JNTUH',
    collegeCode: 'JNTUH',
    description: 'One of India\'s leading technological universities, JNTUH offers undergraduate, postgraduate, and doctoral programs in engineering, technology, and management. It has multiple constituent colleges across Telangana.',
    establishmentYear: 1972,
    collegeType: 'University',
    ownership: 'State University',
    accreditation: 'NAAC A+',
    ranking: { nirf: 101, qs: 0, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 82, placement: 80, roi: 88, research: 85, infrastructure: 78, studentSatisfaction: 80 },
    campusArea: '200+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Kukatpally', village: 'Kukatpally',
    address: 'JNTU Main Road, Kukatpally, Hyderabad, Telangana 500085',
    pinCode: '500085',
    googleMapsCoordinates: { lat: 17.4933, lng: 78.3920 },
    googleMapsUrl: 'https://maps.google.com/?q=JNTU+Hyderabad+Kukatpally',
    contactEmail: 'info@jntuh.ac.in', contactPhone: '040-23056100',
    admissionCell: '040-23058781',
    website: 'https://www.jntuh.ac.in',
    facilities: ['Central Library', 'Digital Classrooms', 'Research Centers', 'Sports Complex', 'Hostels', 'WiFi Campus', 'Medical Center', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Kakatiya University',
    shortName: 'KU',
    collegeCode: 'KU',
    description: 'A state university located in Warangal, established in 1976. Named after the Kakatiya dynasty, it offers courses in arts, sciences, commerce, engineering, and law.',
    establishmentYear: 1976,
    collegeType: 'University',
    ownership: 'State University',
    accreditation: 'NAAC A',
    ranking: { nirf: 150, qs: 0, naacGrade: 'A', nbaAccreditation: false },
    aiScore: { overall: 75, placement: 65, roi: 80, research: 78, infrastructure: 72, studentSatisfaction: 74 },
    campusArea: '1000+ Acres',
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Hanamkonda', village: 'Vidyaranyapuri',
    address: 'Kakatiya University, Vidyaranyapuri, Hanamkonda, Warangal, Telangana 506009',
    pinCode: '506009',
    googleMapsCoordinates: { lat: 18.0006, lng: 79.5780 },
    googleMapsUrl: 'https://maps.google.com/?q=Kakatiya+University+Warangal',
    contactEmail: 'info@kakatiya.ac.in', contactPhone: '0870-2461422',
    website: 'https://www.kakatiya.ac.in',
    facilities: ['Central Library', 'Research Labs', 'Sports Ground', 'Hostels', 'WiFi', 'Medical Center'],
    isVerified: true,
  },
  {
    name: 'Mahatma Gandhi University',
    shortName: 'MGU',
    collegeCode: 'MGU',
    description: 'A state university located in Nalgonda district, established in 2019. Offers undergraduate and postgraduate programs in various disciplines.',
    establishmentYear: 2019,
    collegeType: 'University',
    ownership: 'State University',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 62, placement: 55, roi: 70, research: 60, infrastructure: 65, studentSatisfaction: 68 },
    campusArea: '200+ Acres',
    country: 'India', state: 'Telangana', city: 'Nalgonda', district: 'Nalgonda',
    mandal: 'Nalgonda', village: 'Nalgonda',
    address: 'Mahatma Gandhi University, Nalgonda, Telangana 508001',
    pinCode: '508001',
    contactEmail: 'info@mguniversity.ac.in', contactPhone: '08682-222200',
    website: 'https://www.mguniversity.ac.in',
    facilities: ['Library', 'Labs', 'Hostels', 'Sports', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Palamuru University',
    shortName: 'PU',
    collegeCode: 'PU',
    description: 'A state university located in Mahabubnagar district, established in 2008. Offers a wide range of undergraduate and postgraduate programs.',
    establishmentYear: 2008,
    collegeType: 'University',
    ownership: 'State University',
    accreditation: 'NAAC B',
    ranking: { naacGrade: 'B' },
    aiScore: { overall: 58, placement: 50, roi: 68, research: 55, infrastructure: 60, studentSatisfaction: 62 },
    campusArea: '150+ Acres',
    country: 'India', state: 'Telangana', city: 'Mahabubnagar', district: 'Mahabubnagar',
    mandal: 'Mahabubnagar', village: 'Mahabubnagar',
    address: 'Palamuru University, Mahabubnagar, Telangana 509001',
    pinCode: '509001',
    contactEmail: 'info@palamuruuniversity.ac.in',
    website: 'https://www.palamuruuniversity.ac.in',
    facilities: ['Library', 'Labs', 'Hostels', 'Sports'],
    isVerified: true,
  },
  {
    name: 'Satavahana University',
    shortName: 'SU',
    collegeCode: 'SU',
    description: 'A state university located in Karimnagar, established in 2007. Named after the Satavahana dynasty, it offers various UG and PG programs.',
    establishmentYear: 2007,
    collegeType: 'University',
    ownership: 'State University',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 60, placement: 52, roi: 65, research: 58, infrastructure: 62, studentSatisfaction: 64 },
    campusArea: '120+ Acres',
    country: 'India', state: 'Telangana', city: 'Karimnagar', district: 'Karimnagar',
    mandal: 'Karimnagar', village: 'Karimnagar',
    address: 'Satavahana University, Karimnagar, Telangana 505001',
    pinCode: '505001',
    contactEmail: 'info@satavahana.ac.in',
    website: 'https://www.satavahana.ac.in',
    facilities: ['Library', 'Labs', 'Hostels', 'Sports'],
    isVerified: true,
  },
  {
    name: 'Telangana University',
    shortName: 'TU',
    collegeCode: 'TU',
    description: 'A state university located in Nizamabad district, established in 2006. It aims to provide quality higher education to the region.',
    establishmentYear: 2006,
    collegeType: 'University',
    ownership: 'State University',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 59, placement: 50, roi: 66, research: 56, infrastructure: 61, studentSatisfaction: 63 },
    campusArea: '200+ Acres',
    country: 'India', state: 'Telangana', city: 'Nizamabad', district: 'Nizamabad',
    mandal: 'Nizamabad', village: 'Dichpally',
    address: 'Telangana University, Dichpally, Nizamabad, Telangana 503322',
    pinCode: '503322',
    contactEmail: 'info@telanganauniversity.ac.in',
    website: 'https://www.telanganauniversity.ac.in',
    facilities: ['Library', 'Labs', 'Hostels', 'Sports', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'University of Hyderabad',
    shortName: 'UoH',
    collegeCode: 'UOH',
    description: 'A central university established in 1974, known for its research output and academic excellence. Consistently ranked among the top universities in India with NAAC A++ accreditation.',
    establishmentYear: 1974,
    collegeType: 'University',
    ownership: 'Central University',
    accreditation: 'NAAC A++',
    ranking: { nirf: 8, qs: 651, naacGrade: 'A++', nbaAccreditation: false },
    aiScore: { overall: 90, placement: 75, roi: 82, research: 95, infrastructure: 88, studentSatisfaction: 86 },
    campusArea: '2300+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Gachibowli', village: 'Gachibowli',
    address: 'Prof. C.R. Rao Road, Gachibowli, Hyderabad, Telangana 500046',
    pinCode: '500046',
    googleMapsCoordinates: { lat: 17.4636, lng: 78.3299 },
    googleMapsUrl: 'https://maps.google.com/?q=University+of+Hyderabad+Gachibowli',
    contactEmail: 'info@uohyd.ac.in', contactPhone: '040-23132100',
    website: 'https://www.uohyd.ac.in',
    socialLinks: { facebook: 'https://facebook.com/universityofhyderabad', twitter: 'https://twitter.com/uohyd', linkedin: 'https://linkedin.com/school/university-of-hyderabad' },
    facilities: ['Indira Gandhi Memorial Library', 'Advanced Research Centers', 'Sports Complex', 'Hostels', 'WiFi Campus', 'Medical Center', 'Bank', 'Guest House', 'Auditorium'],
    isVerified: true,
  },
  {
    name: 'National Institute of Technology Warangal',
    shortName: 'NITW',
    collegeCode: 'NITW',
    description: 'One of the premier NITs in India, established in 1959. Known for excellent engineering education, research, and placements. Accredited with NAAC A++ and consistently ranked among top 20 engineering institutes in India.',
    establishmentYear: 1959,
    collegeType: 'University',
    ownership: 'Government',
    accreditation: 'NAAC A++',
    ranking: { nirf: 23, qs: 801, naacGrade: 'A++', nbaAccreditation: true },
    aiScore: { overall: 89, placement: 92, roi: 88, research: 86, infrastructure: 85, studentSatisfaction: 88 },
    campusArea: '250+ Acres',
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Hanamkonda', village: 'NIT Campus',
    address: 'NIT Warangal, Hanamkonda, Warangal, Telangana 506004',
    pinCode: '506004',
    googleMapsCoordinates: { lat: 18.0000, lng: 79.5900 },
    googleMapsUrl: 'https://maps.google.com/?q=NIT+Warangal',
    contactEmail: 'director@nitw.ac.in', contactPhone: '0870-2462000',
    website: 'https://www.nitw.ac.in',
    socialLinks: { facebook: 'https://facebook.com/nitwarangalofficial', twitter: 'https://twitter.com/nitwarangal', linkedin: 'https://linkedin.com/school/nit-warangal' },
    facilities: ['Central Library', 'Advanced Research Labs', 'Sports Stadium', 'Olympic Pool', 'WiFi Campus', 'Medical Center', 'Hostels', 'Guest House', 'Bank', 'Cafeteria', 'Incubation Centre', 'Innovation Lab'],
    isVerified: true,
  },
  {
    name: 'Indian Institute of Technology Hyderabad',
    shortName: 'IITH',
    collegeCode: 'IITH',
    description: 'One of the newer IITs established in 2008, IIT Hyderabad has rapidly grown to become a top-tier engineering institute with cutting-edge research and excellent placement record.',
    establishmentYear: 2008,
    collegeType: 'University',
    ownership: 'Government',
    accreditation: 'NAAC A+',
    ranking: { nirf: 8, qs: 601, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 91, placement: 94, roi: 85, research: 93, infrastructure: 90, studentSatisfaction: 89 },
    campusArea: '576+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Sangareddy',
    mandal: 'Kandi', village: 'Kandi',
    address: 'IIT Hyderabad, Kandi, Sangareddy, Telangana 502285',
    pinCode: '502285',
    googleMapsCoordinates: { lat: 17.5928, lng: 78.1208 },
    googleMapsUrl: 'https://maps.google.com/?q=IIT+Hyderabad+Kandi',
    contactEmail: 'office@iith.ac.in', contactPhone: '040-23016003',
    website: 'https://www.iith.ac.in',
    socialLinks: { facebook: 'https://facebook.com/iithyderabad', twitter: 'https://twitter.com/iithyderabad', linkedin: 'https://linkedin.com/school/iit-hyderabad' },
    facilities: ['Smart Library', 'Research Labs', 'Sports Complex', 'Hostels', 'WiFi Campus', 'Medical Center', 'Incubation Centre', 'Auditorium', 'Guest House'],
    isVerified: true,
  },
  {
    name: 'International Institute of Information Technology Hyderabad',
    shortName: 'IIITH',
    collegeCode: 'IIITH',
    description: 'A premier research university focused on information technology and computer science. Established in 1998, IIIT Hyderabad is known for its strong research culture and industry partnerships.',
    establishmentYear: 1998,
    collegeType: 'University',
    ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    ranking: { nirf: 65, qs: 801, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 87, placement: 90, roi: 82, research: 91, infrastructure: 82, studentSatisfaction: 85 },
    campusArea: '62+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Gachibowli', village: 'Gachibowli',
    address: 'Gachibowli, Hyderabad, Telangana 500032',
    pinCode: '500032',
    googleMapsCoordinates: { lat: 17.4435, lng: 78.3490 },
    googleMapsUrl: 'https://maps.google.com/?q=IIIT+Hyderabad+Gachibowli',
    contactEmail: 'info@iiit.ac.in', contactPhone: '040-66531000',
    website: 'https://www.iiit.ac.in',
    facilities: ['Library', 'Research Centers', 'Sports', 'Hostels', 'WiFi', 'Medical Center', 'Incubation Centre'],
    isVerified: true,
  },
  {
    name: 'Mahindra University',
    shortName: 'MU',
    collegeCode: 'MUEC',
    description: 'A multidisciplinary university established by the Mahindra Group, offering programs in engineering, management, and liberal arts. Known for its industry-connected curriculum.',
    establishmentYear: 2020,
    collegeType: 'University',
    ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 75, placement: 80, roi: 70, research: 65, infrastructure: 88, studentSatisfaction: 78 },
    campusArea: '120+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Bahadurpally', village: 'Bahadurpally',
    address: 'Mahindra University, Bahadurpally, Hyderabad, Telangana 500043',
    pinCode: '500043',
    contactEmail: 'admissions@mahindrauniversity.edu.in', contactPhone: '040-67135100',
    website: 'https://www.mahindrauniversity.edu.in',
    facilities: ['Library', 'Labs', 'Sports Complex', 'Hostels', 'WiFi', 'Incubation Centre'],
    isVerified: true,
  },
  {
    name: 'Anurag University',
    shortName: 'AU',
    collegeCode: 'ANU',
    description: 'A private university offering engineering, pharmacy, and management programs. Known for its strong placement record and modern infrastructure.',
    establishmentYear: 2020,
    collegeType: 'University',
    ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 72, placement: 78, roi: 76, research: 62, infrastructure: 80, studentSatisfaction: 74 },
    campusArea: '100+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Venkatapur', village: 'Ghatkesar',
    address: 'Anurag University, Venkatapur, Ghatkesar, Hyderabad, Telangana 500088',
    pinCode: '500088',
    contactEmail: 'info@anurag.edu.in', contactPhone: '040-67170000',
    website: 'https://www.anurag.edu.in',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria', 'Transport'],
    isVerified: true,
  },
  {
    name: 'Malla Reddy University',
    shortName: 'MRU',
    collegeCode: 'MRU',
    description: 'A private university established in 2020, offering engineering, management, and pharmacy programs with focus on practical learning and placements.',
    establishmentYear: 2020,
    collegeType: 'University',
    ownership: 'Private',
    accreditation: 'NAAC B+',
    ranking: { naacGrade: 'B+' },
    aiScore: { overall: 65, placement: 70, roi: 72, research: 55, infrastructure: 75, studentSatisfaction: 68 },
    campusArea: '80+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Maisammaguda', village: 'Dulapally',
    address: 'Malla Reddy University, Maisammaguda, Dulapally, Hyderabad, Telangana 500100',
    pinCode: '500100',
    contactEmail: 'admissions@mallareddyuniversity.ac.in',
    website: 'https://www.mallareddyuniversity.ac.in',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'SR University',
    shortName: 'SRU',
    collegeCode: 'SRU',
    description: 'A private university in Warangal, offering engineering, management, and health sciences programs. Known for innovative teaching methods.',
    establishmentYear: 2020,
    collegeType: 'University',
    ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 70, placement: 75, roi: 74, research: 60, infrastructure: 78, studentSatisfaction: 72 },
    campusArea: '100+ Acres',
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Hanamkonda', village: 'Ananthasagar',
    address: 'SR University, Ananthasagar, Hanamkonda, Warangal, Telangana 506371',
    pinCode: '506371',
    contactEmail: 'info@sru.edu.in',
    website: 'https://www.sru.edu.in',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Auditorium'],
    isVerified: true,
  },
  {
    name: 'Woxsen University',
    shortName: 'WU',
    collegeCode: 'WOX',
    description: 'A private university located in Kamkole, Sadasivpet, offering programs in engineering, business, design, and liberal arts with a global perspective.',
    establishmentYear: 2020,
    collegeType: 'University',
    ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 73, placement: 76, roi: 68, research: 62, infrastructure: 85, studentSatisfaction: 76 },
    campusArea: '200+ Acres',
    country: 'India', state: 'Telangana', city: 'Sadasivpet', district: 'Sangareddy',
    mandal: 'Sadasivpet', village: 'Kamkole',
    address: 'Woxsen University, Kamkole, Sadasivpet, Sangareddy, Telangana 502345',
    pinCode: '502345',
    contactEmail: 'admissions@woxsen.edu.in',
    website: 'https://www.woxsen.edu.in',
    facilities: ['Library', 'Labs', 'Sports Complex', 'Hostels', 'WiFi', 'Incubation Centre', 'Design Studio'],
    isVerified: true,
  },
  {
    name: 'Professor Jayashankar Telangana State Agricultural University',
    shortName: 'PJTSAU',
    collegeCode: 'PJTS',
    description: 'The premier agricultural university in Telangana, established in 2014. Offers programs in agriculture, horticulture, agricultural engineering, and related fields.',
    establishmentYear: 2014,
    collegeType: 'Agriculture',
    ownership: 'Government',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 72, placement: 65, roi: 78, research: 80, infrastructure: 75, studentSatisfaction: 70 },
    campusArea: '500+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Rajendranagar', village: 'Rajendranagar',
    address: 'PJTSAU, Rajendranagar, Hyderabad, Telangana 500030',
    pinCode: '500030',
    contactEmail: 'registrar@pjtsau.ac.in', contactPhone: '040-24015369',
    website: 'https://www.pjtsau.ac.in',
    facilities: ['Library', 'Research Farms', 'Labs', 'Hostels', 'Sports', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Jawaharlal Nehru Architecture and Fine Arts University',
    shortName: 'JNAFAU',
    collegeCode: 'JNAF',
    description: 'A specialized university focusing on architecture, fine arts, and design. Established in 2008, it is the only university of its kind in Telangana.',
    establishmentYear: 2008,
    collegeType: 'University',
    ownership: 'Government',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 68, placement: 60, roi: 65, research: 70, infrastructure: 72, studentSatisfaction: 66 },
    campusArea: '50+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Masab Tank', village: 'Masab Tank',
    address: 'JNAFAU, Masab Tank, Hyderabad, Telangana 500028',
    pinCode: '500028',
    contactEmail: 'info@jnafau.ac.in', contactPhone: '040-23313331',
    website: 'https://www.jnafau.ac.in',
    facilities: ['Library', 'Design Studios', 'Labs', 'Hostels', 'WiFi', 'Art Gallery'],
    isVerified: true,
  },
  {
    name: 'English and Foreign Languages University',
    shortName: 'EFLU',
    collegeCode: 'EFL',
    description: 'A central university focused on English and foreign language studies. Established in 1958, it is a premier institution for language education in India.',
    establishmentYear: 1958,
    collegeType: 'University',
    ownership: 'Central University',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 76, placement: 62, roi: 70, research: 82, infrastructure: 74, studentSatisfaction: 72 },
    campusArea: '50+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Tarnaka', village: 'Tarnaka',
    address: 'EFLU, Tarnaka, Hyderabad, Telangana 500007',
    pinCode: '500007',
    contactEmail: 'info@efluniversity.ac.in', contactPhone: '040-27098765',
    website: 'https://www.efluniversity.ac.in',
    facilities: ['Library', 'Language Labs', 'Hostels', 'WiFi', 'Sports', 'Auditorium'],
    isVerified: true,
  },
];

