export const telanganaPharmacyColleges = [
  {
    name: 'Sultan-ul-Uloom College of Pharmacy',
    shortName: 'SUCP', collegeCode: 'SUCP',
    description: 'A premier pharmacy college affiliated to JNTUH. Known for quality pharmaceutical education.',
    establishmentYear: 1999, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 68, placement: 70, roi: 74, research: 65, infrastructure: 72, studentSatisfaction: 70 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Banjara Hills', village: 'Banjara Hills',
    address: 'Sultan-ul-Uloom College of Pharmacy, Banjara Hills, Hyderabad, Telangana 500034',
    pinCode: '500034',
    affiliatedUniversity: 'JNTUH',
    website: 'https://www.sultanululoom.org',
    facilities: ['Library', 'Labs', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Malla Reddy College of Pharmacy',
    shortName: 'MRCP', collegeCode: 'MRCP',
    description: 'A pharmacy college affiliated to JNTUH. Part of Malla Reddy group.',
    establishmentYear: 2005, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 65, placement: 68, roi: 72, research: 62, infrastructure: 70, studentSatisfaction: 68 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Maisammaguda', village: 'Dulapally',
    address: 'Malla Reddy College of Pharmacy, Maisammaguda, Hyderabad, Telangana 500100',
    pinCode: '500100',
    affiliatedUniversity: 'JNTUH',
    website: 'https://www.mallareddypharmacy.ac.in',
    facilities: ['Library', 'Labs', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'CMR College of Pharmacy',
    shortName: 'CMRCP', collegeCode: 'CMRP',
    description: 'A pharmacy college affiliated to JNTUH. Part of CMR group of institutions.',
    establishmentYear: 2008, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 66, placement: 69, roi: 72, research: 63, infrastructure: 71, studentSatisfaction: 68 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Kandlakoya',
    address: 'CMR College of Pharmacy, Kandlakoya, Medchal, Hyderabad, Telangana 501401',
    pinCode: '501401',
    affiliatedUniversity: 'JNTUH',
    website: 'https://www.cmrpharmacy.ac.in',
    facilities: ['Library', 'Labs', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'St. Paul\'s College of Pharmacy',
    shortName: 'SPCP', collegeCode: 'SPCP',
    description: 'A pharmacy college affiliated to JNTUH. Known for quality pharmacy education.',
    establishmentYear: 2002, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 65, placement: 67, roi: 71, research: 62, infrastructure: 69, studentSatisfaction: 67 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Hyderabad',
    address: 'St. Paul\'s College of Pharmacy, Hyderabad, Telangana 500001',
    pinCode: '500001',
    affiliatedUniversity: 'Osmania University',
    website: 'https://www.stpaulspharmacy.edu.in',
    facilities: ['Library', 'Labs', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Princeton College of Pharmacy',
    shortName: 'PCP', collegeCode: 'PCP',
    description: 'A pharmacy college located in Ghatkesar, Hyderabad.',
    establishmentYear: 2008, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC B++',
    aiScore: { overall: 62, placement: 65, roi: 70, research: 59, infrastructure: 67, studentSatisfaction: 64 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Ghatkesar', village: 'Ghatkesar',
    address: 'Princeton College of Pharmacy, Ghatkesar, Hyderabad, Telangana 501301',
    pinCode: '501301',
    affiliatedUniversity: 'JNTUH',
    website: 'https://www.princetonpharmacy.ac.in',
    facilities: ['Library', 'Labs'],
    isVerified: true,
  },
  {
    name: 'Gokaraju Rangaraju College of Pharmacy',
    shortName: 'GRCP', collegeCode: 'GRCP',
    description: 'A pharmacy college affiliated to JNTUH. Part of Gokaraju group.',
    establishmentYear: 2005, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 66, placement: 68, roi: 72, research: 64, infrastructure: 70, studentSatisfaction: 67 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Bachupally', village: 'Kukatpally',
    address: 'GRCP, Bachupally, Hyderabad, Telangana 500090',
    pinCode: '500090',
    affiliatedUniversity: 'JNTUH',
    website: 'https://www.grcp.ac.in',
    facilities: ['Library', 'Labs', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Vaagdevi College of Pharmacy',
    shortName: 'VCP', collegeCode: 'VCP',
    description: 'A pharmacy college located in Warangal.',
    establishmentYear: 2005, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 65, placement: 67, roi: 71, research: 62, infrastructure: 69, studentSatisfaction: 67 },
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Hanamkonda', village: 'Hanamkonda',
    address: 'Vaagdevi College of Pharmacy, Hanamkonda, Warangal, Telangana 506005',
    pinCode: '506005',
    affiliatedUniversity: 'Kakatiya University',
    website: 'https://www.vaagdevipharmacy.ac.in',
    facilities: ['Library', 'Labs', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Talla Padmavathi College of Pharmacy',
    shortName: 'TPCP', collegeCode: 'TPCP',
    description: 'A pharmacy college located in Warangal.',
    establishmentYear: 2008, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC B++',
    aiScore: { overall: 61, placement: 64, roi: 69, research: 58, infrastructure: 66, studentSatisfaction: 63 },
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Warangal', village: 'Warangal',
    address: 'TPCP, Warangal, Telangana 506002',
    pinCode: '506002',
    affiliatedUniversity: 'Kakatiya University',
    website: 'https://www.tpcp.ac.in',
    facilities: ['Library', 'Labs'],
    isVerified: true,
  },
  {
    name: 'Teegala Krishna Reddy College of Pharmacy',
    shortName: 'TKRCP', collegeCode: 'TKRCP',
    description: 'A pharmacy college affiliated to JNTUH. Located in Meerpet, Hyderabad.',
    establishmentYear: 2008, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC B++',
    aiScore: { overall: 62, placement: 65, roi: 69, research: 59, infrastructure: 67, studentSatisfaction: 64 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Meerpet', village: 'Meerpet',
    address: 'TKRCP, Meerpet, Hyderabad, Telangana 500097',
    pinCode: '500097',
    affiliatedUniversity: 'JNTUH',
    website: 'https://www.tkrcp.ac.in',
    facilities: ['Library', 'Labs'],
    isVerified: true,
  },
  {
    name: 'Vignan Institute of Pharmaceutical Technology',
    shortName: 'VIPT', collegeCode: 'VIPT',
    description: 'A pharmacy college affiliated to JNTUH. Located in Guntur border area.',
    establishmentYear: 2005, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 66, placement: 68, roi: 71, research: 63, infrastructure: 70, studentSatisfaction: 67 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Deshmukhi',
    address: 'VIPT, Deshmukhi, Hyderabad, Telangana 501301',
    pinCode: '501301',
    affiliatedUniversity: 'JNTUH',
    website: 'https://www.vipt.ac.in',
    facilities: ['Library', 'Labs', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Bharat Institute of Pharmacy',
    shortName: 'BIP', collegeCode: 'BIP',
    description: 'A pharmacy college located in Ibrahimpatnam, Hyderabad.',
    establishmentYear: 2005, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC B++',
    aiScore: { overall: 61, placement: 64, roi: 69, research: 58, infrastructure: 66, studentSatisfaction: 63 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Ibrahimpatnam', village: 'Ibrahimpatnam',
    address: 'Bharat Institute of Pharmacy, Ibrahimpatnam, Hyderabad, Telangana 501506',
    pinCode: '501506',
    affiliatedUniversity: 'JNTUH',
    website: 'https://www.bharatpharmacy.ac.in',
    facilities: ['Library', 'Labs'],
    isVerified: true,
  },
  {
    name: 'Shadan College of Pharmacy',
    shortName: 'SCP', collegeCode: 'SCP',
    description: 'A pharmacy college affiliated to JNTUH. Located in Hyderabad.',
    establishmentYear: 2005, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 64, placement: 66, roi: 70, research: 61, infrastructure: 68, studentSatisfaction: 66 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Hyderabad', village: 'Hyderabad',
    address: 'Shadan College of Pharmacy, Hyderabad, Telangana 500001',
    pinCode: '500001',
    affiliatedUniversity: 'JNTUH',
    website: 'https://www.shadanpharmacy.ac.in',
    facilities: ['Library', 'Labs', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'MESCO College of Pharmacy',
    shortName: 'MCP', collegeCode: 'MCP',
    description: 'A pharmacy college affiliated to JNTUH. Located in Hyderabad.',
    establishmentYear: 2008, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC B++',
    aiScore: { overall: 62, placement: 64, roi: 68, research: 59, infrastructure: 66, studentSatisfaction: 64 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Hyderabad',
    address: 'MESCO College of Pharmacy, Hyderabad, Telangana 500001',
    pinCode: '500001',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs'],
    isVerified: true,
  },
  {
    name: 'Anurag Pharmacy College',
    shortName: 'APC', collegeCode: 'APC',
    description: 'A pharmacy college affiliated to JNTUH. Part of Anurag group.',
    establishmentYear: 2008, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 65, placement: 67, roi: 71, research: 62, infrastructure: 69, studentSatisfaction: 66 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Venkatapur', village: 'Ghatkesar',
    address: 'Anurag Pharmacy College, Venkatapur, Hyderabad, Telangana 500088',
    pinCode: '500088',
    affiliatedUniversity: 'JNTUH',
    website: 'https://www.anuragpharmacy.ac.in',
    facilities: ['Library', 'Labs', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'SVS Group of Institutions (Pharmacy)',
    shortName: 'SVSP', collegeCode: 'SVSP',
    description: 'Pharmacy programs under SVS Group of Institutions in Warangal.',
    establishmentYear: 2002, collegeType: 'Pharmacy', ownership: 'Private',
    accreditation: 'NAAC B++',
    aiScore: { overall: 60, placement: 63, roi: 68, research: 57, infrastructure: 64, studentSatisfaction: 62 },
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Hanamkonda', village: 'Hanamkonda',
    address: 'SVS Pharmacy, Hanamkonda, Warangal, Telangana 506005',
    pinCode: '506005',
    affiliatedUniversity: 'Kakatiya University',
    facilities: ['Library', 'Labs'],
    isVerified: true,
  },
];

