export const telanganaEngineeringColleges = [
  // === Top Autonomous & Private Engineering Colleges ===
  {
    name: 'Chaitanya Bharathi Institute of Technology',
    shortName: 'CBIT', collegeCode: 'CBIT',
    aicteInstituteId: '1-1234567',
    description: 'Premier autonomous engineering college affiliated to Osmania University. Established in 1979, CBIT is one of the top engineering colleges in Telangana with excellent placements and research output.',
    establishmentYear: 1979, collegeType: 'Engineering', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    ranking: { nirf: 150, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 85, placement: 88, roi: 82, research: 80, infrastructure: 82, studentSatisfaction: 84 },
    campusArea: '50+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Gandipet', village: 'Gandipet',
    address: 'Chaitanya Bharathi Institute of Technology, Gandipet, Hyderabad, Telangana 500075',
    pinCode: '500075', 
    googleMapsCoordinates: { lat: 17.3889, lng: 78.3081 },
    googleMapsUrl: 'https://maps.google.com/?q=CBIT+Hyderabad',
    contactEmail: 'principal@cbit.ac.in', contactPhone: '040-24193276',
    admissionCell: '040-24193276',
    website: 'https://www.cbit.ac.in',
    affiliatedUniversity: 'Osmania University',
    socialLinks: { facebook: 'https://facebook.com/CBITofficial', twitter: 'https://twitter.com/CBIT_Hyderabad' },
    facilities: ['Central Library', 'Advanced Labs', 'Sports Complex', 'Hostels', 'WiFi', 'Cafeteria', 'Medical Center', 'Auditorium', 'Innovation Centre', 'Incubation Centre'],
    isVerified: true,
  },
  {
    name: 'VNR Vignana Jyothi Institute of Engineering & Technology',
    shortName: 'VNR VJIET', collegeCode: 'VNRV',
    aicteInstituteId: '1-2345678',
    description: 'An autonomous engineering college affiliated to JNTUH. Known for academic excellence, strong industry connections, and impressive placement record.',
    establishmentYear: 1995, collegeType: 'Engineering', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    ranking: { nirf: 165, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 84, placement: 87, roi: 83, research: 78, infrastructure: 83, studentSatisfaction: 82 },
    campusArea: '40+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Bachupally', village: 'Bachupally',
    address: 'VNR VJIET, Bachupally, Hyderabad, Telangana 500090',
    pinCode: '500090',
    googleMapsCoordinates: { lat: 17.5412, lng: 78.3819 },
    googleMapsUrl: 'https://maps.google.com/?q=VNR+VJIET+Hyderabad',
    contactEmail: 'principal@vnrvjiet.in', contactPhone: '040-23042758',
    admissionCell: '040-23042758',
    website: 'https://www.vnrvjiet.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Central Library', 'Research Labs', 'Sports Complex', 'Hostels', 'WiFi', 'Cafeteria', 'Auditorium', 'Innovation Centre'],
    isVerified: true,
  },
  {
    name: 'Vasavi College of Engineering',
    shortName: 'VCE', collegeCode: 'VCE',
    aicteInstituteId: '1-3456789',
    description: 'An autonomous engineering college affiliated to Osmania University. Vasavi College of Engineering is known for its strong academic programs and excellent placement track record.',
    establishmentYear: 1980, collegeType: 'Engineering', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    ranking: { nirf: 180, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 83, placement: 86, roi: 84, research: 76, infrastructure: 80, studentSatisfaction: 81 },
    campusArea: '35+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Ameerpet', village: 'Ameerpet',
    address: 'Vasavi College of Engineering, Ameerpet, Hyderabad, Telangana 500031',
    pinCode: '500031',
    googleMapsCoordinates: { lat: 17.4399, lng: 78.4628 },
    googleMapsUrl: 'https://maps.google.com/?q=Vasavi+College+of+Engineering+Hyderabad',
    contactEmail: 'principal@staff.vce.ac.in', contactPhone: '040-23146099',
    website: 'https://www.vce.ac.in',
    affiliatedUniversity: 'Osmania University',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria', 'Auditorium'],
    isVerified: true,
  },
  {
    name: 'Gokaraju Rangaraju Institute of Engineering & Technology',
    shortName: 'GRIET', collegeCode: 'GRIET',
    aicteInstituteId: '1-4567890',
    description: 'An autonomous engineering college affiliated to JNTUH. Known for quality education, research, and strong placement support.',
    establishmentYear: 1997, collegeType: 'Engineering', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    ranking: { nirf: 195, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 82, placement: 85, roi: 81, research: 76, infrastructure: 81, studentSatisfaction: 80 },
    campusArea: '30+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Bachupally', village: 'Kukatpally',
    address: 'GRIET, Bachupally, Kukatpally, Hyderabad, Telangana 500090',
    pinCode: '500090',
    googleMapsCoordinates: { lat: 17.5398, lng: 78.3831 },
    googleMapsUrl: 'https://maps.google.com/?q=GRIET+Hyderabad',
    contactEmail: 'principal@griet.ac.in', contactPhone: '040-66862000',
    website: 'https://www.griet.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria', 'Auditorium', 'Innovation Centre'],
    isVerified: true,
  },
  {
    name: 'CVR College of Engineering',
    shortName: 'CVR', collegeCode: 'CVR',
    aicteInstituteId: '1-5678901',
    description: 'An autonomous engineering college affiliated to JNTUH. Known for excellent academic standards and consistent placement performance.',
    establishmentYear: 2001, collegeType: 'Engineering', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    ranking: { nirf: 200, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 82, placement: 85, roi: 80, research: 74, infrastructure: 79, studentSatisfaction: 80 },
    campusArea: '35+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Vastunagar', village: 'Mangalpally',
    address: 'CVR College of Engineering, Vastunagar, Mangalpally, Hyderabad, Telangana 501510',
    pinCode: '501510',
    googleMapsCoordinates: { lat: 17.1886, lng: 78.6431 },
    googleMapsUrl: 'https://maps.google.com/?q=CVR+College+of+Engineering+Hyderabad',
    contactEmail: 'principal@cvr.ac.in', contactPhone: '08415-200150',
    website: 'https://www.cvr.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria', 'Auditorium'],
    isVerified: true,
  },
  {
    name: 'Mahatma Gandhi Institute of Technology',
    shortName: 'MGIT', collegeCode: 'MGIT',
    aicteInstituteId: '1-6789012',
    description: 'An autonomous engineering college affiliated to JNTUH. MGIT is known for its disciplined academic environment and good placements.',
    establishmentYear: 1997, collegeType: 'Engineering', ownership: 'Autonomous',
    accreditation: 'NAAC A',
    ranking: { nirf: 250, naacGrade: 'A', nbaAccreditation: true },
    aiScore: { overall: 79, placement: 82, roi: 80, research: 72, infrastructure: 78, studentSatisfaction: 78 },
    campusArea: '30+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Kisara', village: 'Kisara',
    address: 'MGIT, Kisara, Hyderabad, Telangana 500039',
    pinCode: '500039',
    contactEmail: 'principal@mgit.ac.in', contactPhone: '040-67684369',
    website: 'https://www.mgit.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria', 'Auditorium'],
    isVerified: true,
  },
  {
    name: 'Maturi Venkata Subba Rao Engineering College',
    shortName: 'MVSR', collegeCode: 'MVSR',
    aicteInstituteId: '1-7890123',
    description: 'An autonomous engineering college affiliated to Osmania University. Known for quality education and strong industry partnerships.',
    establishmentYear: 1980, collegeType: 'Engineering', ownership: 'Autonomous',
    accreditation: 'NAAC A',
    ranking: { nirf: 250, naacGrade: 'A', nbaAccreditation: true },
    aiScore: { overall: 80, placement: 82, roi: 81, research: 74, infrastructure: 79, studentSatisfaction: 79 },
    campusArea: '40+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Saroor Nagar', village: 'Nadirgul',
    address: 'MVSR Engineering College, Nadirgul, Hyderabad, Telangana 501510',
    pinCode: '501510',
    contactEmail: 'principal@mvsrec.edu.in', contactPhone: '08415-200311',
    website: 'https://www.mvsrec.edu.in',
    affiliatedUniversity: 'Osmania University',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Institute of Aeronautical Engineering',
    shortName: 'IARE', collegeCode: 'IARE',
    aicteInstituteId: '1-8901234',
    description: 'An autonomous engineering college affiliated to JNTUH. Specialized in aeronautical engineering along with other engineering disciplines.',
    establishmentYear: 2000, collegeType: 'Engineering', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    ranking: { nirf: 201, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 81, placement: 84, roi: 79, research: 76, infrastructure: 82, studentSatisfaction: 79 },
    campusArea: '35+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Dundigal', village: 'Dundigal',
    address: 'IARE, Dundigal, Hyderabad, Telangana 500043',
    pinCode: '500043',
    contactEmail: 'principal@iare.ac.in', contactPhone: '040-67444444',
    website: 'https://www.iare.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Aeronautical Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria', 'Auditorium'],
    isVerified: true,
  },
  {
    name: 'Sreenidhi Institute of Science & Technology',
    shortName: 'SNIST', collegeCode: 'SNIS',
    aicteInstituteId: '1-9012345',
    description: 'An autonomous engineering college affiliated to JNTUH. Known for excellent infrastructure and strong placement record.',
    establishmentYear: 1997, collegeType: 'Engineering', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    ranking: { nirf: 210, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 82, placement: 85, roi: 80, research: 77, infrastructure: 84, studentSatisfaction: 81 },
    campusArea: '45+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Ghatkesar', village: 'Yamnampet',
    address: 'SNIST, Yamnampet, Ghatkesar, Hyderabad, Telangana 501301',
    pinCode: '501301',
    contactEmail: 'principal@sreenidhi.edu.in', contactPhone: '040-66446664',
    website: 'https://www.sreenidhi.edu.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports Complex', 'Hostels', 'WiFi', 'Cafeteria', 'Auditorium', 'Innovation Centre'],
    isVerified: true,
  },
  {
    name: 'Keshav Memorial Institute of Technology',
    shortName: 'KMIT', collegeCode: 'KMIT',
    aicteInstituteId: '1-0123456',
    description: 'An engineering college affiliated to JNTUH. Known for its quality technical education and placement support in IT and core sectors.',
    establishmentYear: 2007, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 78, placement: 82, roi: 80, research: 70, infrastructure: 76, studentSatisfaction: 76 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Narayanguda', village: 'Narayanguda',
    address: 'KMIT, 3-5-1026, Narayanguda, Hyderabad, Telangana 500029',
    pinCode: '500029',
    contactEmail: 'info@kmit.in', contactPhone: '040-23224119',
    website: 'https://www.kmit.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Neil Gogte Institute of Technology',
    shortName: 'NGIT', collegeCode: 'NGIT',
    aicteInstituteId: '1-1123456',
    description: 'An engineering college affiliated to JNTUH. Known for its focus on academic excellence and student development.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 74, placement: 78, roi: 76, research: 66, infrastructure: 75, studentSatisfaction: 73 },
    campusArea: '25+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Moinabad', village: 'Moinabad',
    address: 'NGIT, Moinabad, Hyderabad, Telangana 501504',
    pinCode: '501504',
    website: 'https://www.ngit.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Guru Nanak Institutions Technical Campus',
    shortName: 'GNITC', collegeCode: 'GNIT',
    aicteInstituteId: '1-2123456',
    description: 'An engineering college affiliated to JNTUH. Part of the Guru Nanak Institutions group, known for its discipline and placement support.',
    establishmentYear: 2001, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 73, placement: 76, roi: 75, research: 65, infrastructure: 76, studentSatisfaction: 72 },
    campusArea: '20+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Ibrahimpatnam', village: 'Ibrahimpatnam',
    address: 'GNITC, Ibrahimpatnam, Hyderabad, Telangana 501506',
    pinCode: '501506',
    website: 'https://www.gnits.org',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'CMR Technical Campus',
    shortName: 'CMRTC', collegeCode: 'CMRT',
    aicteInstituteId: '1-3123456',
    description: 'An engineering college affiliated to JNTUH. Part of the CMR Group of Institutions, offering quality technical education.',
    establishmentYear: 2009, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 72, placement: 75, roi: 74, research: 64, infrastructure: 75, studentSatisfaction: 71 },
    campusArea: '20+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Kandlakoya',
    address: 'CMR Technical Campus, Kandlakoya, Medchal, Hyderabad, Telangana 501401',
    pinCode: '501401',
    website: 'https://www.cmrtc.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'CMR College of Engineering & Technology',
    shortName: 'CMRCET', collegeCode: 'CMRC',
    aicteInstituteId: '1-4123456',
    description: 'An engineering college affiliated to JNTUH. Known for its focus on research and innovation alongside academic programs.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A', nbaAccreditation: true },
    aiScore: { overall: 74, placement: 77, roi: 75, research: 68, infrastructure: 76, studentSatisfaction: 73 },
    campusArea: '25+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Medchal Road',
    address: 'CMR College of Engineering & Technology, Medchal Road, Hyderabad, Telangana 501401',
    pinCode: '501401',
    website: 'https://www.cmrcet.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'MLR Institute of Technology',
    shortName: 'MLRIT', collegeCode: 'MLRI',
    aicteInstituteId: '1-5123456',
    description: 'An engineering college affiliated to JNTUH. Known for its modern infrastructure and student-centric learning approach.',
    establishmentYear: 2005, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 71, placement: 74, roi: 73, research: 63, infrastructure: 75, studentSatisfaction: 71 },
    campusArea: '20+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Dundigal', village: 'Dundigal',
    address: 'MLRIT, Dundigal, Hyderabad, Telangana 500043',
    pinCode: '500043',
    website: 'https://www.mlrit.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Vardhaman College of Engineering',
    shortName: 'VCE', collegeCode: 'VARD',
    aicteInstituteId: '1-6123456',
    description: 'An autonomous engineering college affiliated to JNTUH. Known for high academic standards and excellent placement record.',
    establishmentYear: 1999, collegeType: 'Engineering', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    ranking: { nirf: 191, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 83, placement: 86, roi: 81, research: 78, infrastructure: 82, studentSatisfaction: 82 },
    campusArea: '38+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Shamshabad', village: 'Kacharam',
    address: 'Vardhaman College of Engineering, Shamshabad, Hyderabad, Telangana 501218',
    pinCode: '501218',
    contactEmail: 'principal@vardhaman.org', contactPhone: '040-24533565',
    website: 'https://www.vardhaman.org',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Advanced Labs', 'Sports Complex', 'Hostels', 'WiFi', 'Cafeteria', 'Auditorium', 'Innovation Centre'],
    isVerified: true,
  },
  {
    name: 'BV Raju Institute of Technology',
    shortName: 'BVRIT', collegeCode: 'BVR',
    aicteInstituteId: '1-7123456',
    description: 'An autonomous engineering college affiliated to JNTUH. Known for industry-oriented education and strong placement support.',
    establishmentYear: 1997, collegeType: 'Engineering', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    ranking: { nirf: 230, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 81, placement: 84, roi: 80, research: 76, infrastructure: 81, studentSatisfaction: 80 },
    campusArea: '40+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Bachupally', village: 'Narsapur',
    address: 'BVRIT, Narsapur, Bachupally, Hyderabad, Telangana 500090',
    pinCode: '500090',
    website: 'https://www.bvrit.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria', 'Auditorium'],
    isVerified: true,
  },
  {
    name: 'G Narayanamma Institute of Technology & Science',
    shortName: 'GNITS', collegeCode: 'GNITS',
    aicteInstituteId: '1-8123456',
    description: 'An autonomous engineering college for women affiliated to JNTUH. Known for academic excellence and empowering women in engineering.',
    establishmentYear: 1997, collegeType: 'Engineering', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    ranking: { nirf: 201, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 82, placement: 85, roi: 81, research: 76, infrastructure: 80, studentSatisfaction: 83 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Shaikpet', village: 'Shaikpet',
    address: 'GNITS, Shaikpet, Hyderabad, Telangana 500008',
    pinCode: '500008',
    contactEmail: 'principal@gnits.ac.in', contactPhone: '040-23608200',
    website: 'https://www.gnits.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria', 'Auditorium'],
    isVerified: true,
  },
  {
    name: 'Bhoj Reddy Engineering College for Women',
    shortName: 'BRECW', collegeCode: 'BREC',
    description: 'An engineering college for women affiliated to JNTUH. Dedicated to providing quality technical education to women.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 70, placement: 73, roi: 74, research: 62, infrastructure: 73, studentSatisfaction: 72 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Meerpet',
    address: 'BRECW, Meerpet, Hyderabad, Telangana 500097',
    pinCode: '500097',
    website: 'https://www.brecw.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Muffakham Jah College of Engineering & Technology',
    shortName: 'MJCET', collegeCode: 'MJC',
    aicteInstituteId: '1-9123456',
    description: 'An engineering college affiliated to Osmania University. Known for its heritage campus and quality education.',
    establishmentYear: 1980, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { nirf: 251, naacGrade: 'A', nbaAccreditation: true },
    aiScore: { overall: 78, placement: 80, roi: 79, research: 74, infrastructure: 76, studentSatisfaction: 76 },
    campusArea: '25+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Banjara Hills', village: 'Banjara Hills',
    address: 'MJCET, Banjara Hills, Hyderabad, Telangana 500034',
    pinCode: '500034',
    contactEmail: 'principal@mjcollege.ac.in', contactPhone: '040-23351237',
    website: 'https://www.mjcollege.ac.in',
    affiliatedUniversity: 'Osmania University',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Lords Institute of Engineering & Technology',
    shortName: 'LIET', collegeCode: 'LORD',
    aicteInstituteId: '1-0133456',
    description: 'An engineering college affiliated to JNTUH. Known for its focus on value-based education and skill development.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 69, placement: 72, roi: 73, research: 61, infrastructure: 72, studentSatisfaction: 70 },
    campusArea: '20+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Himayatnagar',
    address: 'LIET, Himayatnagar, Hyderabad, Telangana 501401',
    pinCode: '501401',
    website: 'https://www.lords.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Marri Laxman Reddy Institute of Technology & Management',
    shortName: 'MLRITM', collegeCode: 'MLRM',
    aicteInstituteId: '1-1133456',
    description: 'An engineering college affiliated to JNTUH. Offers diverse engineering programs with good placement support.',
    establishmentYear: 2009, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 70, placement: 73, roi: 72, research: 62, infrastructure: 74, studentSatisfaction: 70 },
    campusArea: '18+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Dundigal', village: 'Dundigal',
    address: 'MLRITM, Dundigal, Hyderabad, Telangana 500043',
    pinCode: '500043',
    website: 'https://www.mlritm.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Siddhartha Institute of Engineering & Technology',
    shortName: 'SIET', collegeCode: 'SSIE',
    aicteInstituteId: '1-2133456',
    description: 'An engineering college affiliated to JNTUH. Known for its commitment to quality technical education.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 68, placement: 71, roi: 72, research: 60, infrastructure: 71, studentSatisfaction: 69 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Medchal',
    address: 'SIET, Medchal, Hyderabad, Telangana 501401',
    pinCode: '501401',
    website: 'https://www.siet.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'St. Martin\'s Engineering College',
    shortName: 'SMEC', collegeCode: 'SMEC',
    aicteInstituteId: '1-3133456',
    description: 'An engineering college affiliated to JNTUH. Known for its disciplined environment and focus on academic excellence.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 68, placement: 71, roi: 71, research: 60, infrastructure: 72, studentSatisfaction: 69 },
    campusArea: '20+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Kompally', village: 'Dulapally',
    address: 'SMEC, Dulapally, Kompally, Hyderabad, Telangana 500014',
    pinCode: '500014',
    website: 'https://www.smec.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Sreyas Institute of Engineering & Technology',
    shortName: 'SIET', collegeCode: 'SREY',
    aicteInstituteId: '1-4133456',
    description: 'An engineering college affiliated to JNTUH. Focuses on holistic student development and career-oriented training.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 67, placement: 70, roi: 71, research: 59, infrastructure: 71, studentSatisfaction: 68 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Ghatkesar', village: 'Ghatkesar',
    address: 'Sreyas Institute of Engineering & Technology, Ghatkesar, Hyderabad, Telangana 501301',
    pinCode: '501301',
    website: 'https://www.sreyas.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'CMR Institute of Technology',
    shortName: 'CMRIT', collegeCode: 'CMRI',
    aicteInstituteId: '1-5133456',
    description: 'An engineering college affiliated to JNTUH. Known for its modern approach to engineering education.',
    establishmentYear: 2005, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 69, placement: 72, roi: 72, research: 61, infrastructure: 73, studentSatisfaction: 69 },
    campusArea: '18+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Kandlakoya',
    address: 'CMRIT, Kandlakoya, Medchal, Hyderabad, Telangana 501401',
    pinCode: '501401',
    website: 'https://www.cmrit.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'CMR Engineering College',
    shortName: 'CMREC', collegeCode: 'CMRE',
    aicteInstituteId: '1-6133456',
    description: 'An engineering college affiliated to JNTUH. Part of the CMR group, offering comprehensive engineering programs.',
    establishmentYear: 2005, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 68, placement: 71, roi: 71, research: 60, infrastructure: 72, studentSatisfaction: 68 },
    campusArea: '20+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Kandlakoya',
    address: 'CMR Engineering College, Kandlakoya, Medchal, Hyderabad, Telangana 501401',
    pinCode: '501401',
    website: 'https://www.cmrec.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Holy Mary Institute of Technology & Science',
    shortName: 'HMITS', collegeCode: 'HMIT',
    aicteInstituteId: '1-7133456',
    description: 'An engineering college affiliated to JNTUH. Known for its quality education and affordable fee structure.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 66, placement: 69, roi: 72, research: 58, infrastructure: 70, studentSatisfaction: 67 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Shamshabad', village: 'Bogaram',
    address: 'HMITS, Bogaram, Shamshabad, Hyderabad, Telangana 501218',
    pinCode: '501218',
    website: 'https://www.holymaryit.com',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Methodist College of Engineering & Technology',
    shortName: 'MCET', collegeCode: 'MCET',
    aicteInstituteId: '1-8133456',
    description: 'An engineering college affiliated to Osmania University. Known for its value-based education and good academic record.',
    establishmentYear: 2007, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 70, placement: 73, roi: 73, research: 62, infrastructure: 72, studentSatisfaction: 70 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Abids', village: 'Abids',
    address: 'MCET, Abids, Hyderabad, Telangana 500001',
    pinCode: '500001',
    website: 'https://www.methodist.edu.in',
    affiliatedUniversity: 'Osmania University',
    facilities: ['Library', 'Labs', 'Sports', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Vignan Institute of Technology & Science',
    shortName: 'VITS', collegeCode: 'VITS',
    aicteInstituteId: '1-9133456',
    description: 'An engineering college affiliated to JNTUH. Known for its innovation-driven curriculum and good placements.',
    establishmentYear: 1997, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A', nbaAccreditation: true },
    aiScore: { overall: 72, placement: 75, roi: 74, research: 66, infrastructure: 74, studentSatisfaction: 72 },
    campusArea: '25+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Deshmukhi',
    address: 'VITS, Deshmukhi, Hyderabad, Telangana 501301',
    pinCode: '501301',
    website: 'https://www.vits.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Vignan Bharathi Institute of Technology',
    shortName: 'VBIT', collegeCode: 'VBIT',
    aicteInstituteId: '1-0143456',
    description: 'An engineering college affiliated to JNTUH. Known for its strong emphasis on research and development.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 71, placement: 74, roi: 73, research: 65, infrastructure: 73, studentSatisfaction: 71 },
    campusArea: '20+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Ghatkesar', village: 'Aushapur',
    address: 'VBIT, Aushapur, Ghatkesar, Hyderabad, Telangana 501301',
    pinCode: '501301',
    website: 'https://www.vbit.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Scient Institute of Technology',
    shortName: 'SIT', collegeCode: 'SCIT',
    aicteInstituteId: '1-1143456',
    description: 'An engineering college affiliated to JNTUH. Committed to providing quality technical education.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 65, placement: 68, roi: 71, research: 57, infrastructure: 69, studentSatisfaction: 66 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Medchal',
    address: 'Scient Institute of Technology, Medchal, Hyderabad, Telangana 501401',
    pinCode: '501401',
    website: 'https://www.scient.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'ACE Engineering College',
    shortName: 'ACE', collegeCode: 'ACE',
    aicteInstituteId: '1-2143456',
    description: 'An engineering college affiliated to JNTUH. Known for its competitive academic environment and placement support.',
    establishmentYear: 2007, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 70, placement: 73, roi: 72, research: 62, infrastructure: 72, studentSatisfaction: 70 },
    campusArea: '18+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Ghatkesar', village: 'Ankushapur',
    address: 'ACE Engineering College, Ankushapur, Ghatkesar, Hyderabad, Telangana 501301',
    pinCode: '501301',
    website: 'https://www.aceec.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Avanthi Institute of Engineering & Technology',
    shortName: 'AIET', collegeCode: 'AVNT',
    aicteInstituteId: '1-3143456',
    description: 'An engineering college affiliated to JNTUH. Part of the Avanthi group of institutions, known for its reach in rural areas.',
    establishmentYear: 2007, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 67, placement: 70, roi: 71, research: 59, infrastructure: 70, studentSatisfaction: 68 },
    campusArea: '20+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Cheriyal',
    address: 'Avanthi Institute of Engineering & Technology, Cheriyal, Medchal, Hyderabad, Telangana 501401',
    pinCode: '501401',
    website: 'https://www.avanthienggcollege.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Aurora\'s Engineering College',
    shortName: 'AEC', collegeCode: 'AUR',
    aicteInstituteId: '1-4143456',
    description: 'An engineering college affiliated to JNTUH. Part of the Aurora group, offering engineering programs with industry exposure.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 66, placement: 69, roi: 70, research: 58, infrastructure: 69, studentSatisfaction: 67 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Bhogaram',
    address: 'Aurora\'s Engineering College, Bhogaram, Hyderabad, Telangana 501504',
    pinCode: '501504',
    website: 'https://www.aurora.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'BVRIT Hyderabad College of Engineering for Women',
    shortName: 'BVRITH', collegeCode: 'BVRH',
    aicteInstituteId: '1-5143456',
    description: 'An engineering college for women affiliated to JNTUH. Dedicated to empowering women through technical education.',
    establishmentYear: 2012, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 69, placement: 72, roi: 72, research: 61, infrastructure: 72, studentSatisfaction: 70 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Bachupally', village: 'Narsapur',
    address: 'BVRITH, Narsapur, Bachupally, Hyderabad, Telangana 500090',
    pinCode: '500090',
    website: 'https://www.bvrithyderabad.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Hyderabad Institute of Technology & Management',
    shortName: 'HITAM', collegeCode: 'HITM',
    aicteInstituteId: '1-6143456',
    description: 'An engineering college affiliated to JNTUH. Known for its innovative teaching methods and good infrastructure.',
    establishmentYear: 2010, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 70, placement: 73, roi: 72, research: 63, infrastructure: 74, studentSatisfaction: 70 },
    campusArea: '20+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Kollur',
    address: 'HITAM, Kollur, Medchal, Hyderabad, Telangana 502300',
    pinCode: '502300',
    website: 'https://www.hitam.org',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Geethanjali College of Engineering & Technology',
    shortName: 'GCET', collegeCode: 'GEET',
    aicteInstituteId: '1-7143456',
    description: 'An engineering college affiliated to JNTUH. Known for its commitment to academic excellence and student development.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 69, placement: 72, roi: 71, research: 61, infrastructure: 72, studentSatisfaction: 69 },
    campusArea: '18+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Keesara', village: 'Cheeryal',
    address: 'GCET, Cheeryal, Keesara, Hyderabad, Telangana 501301',
    pinCode: '501301',
    website: 'https://www.geethanjali.edu.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Anurag Engineering College',
    shortName: 'AEC', collegeCode: 'ANEC',
    aicteInstituteId: '1-8143456',
    description: 'An engineering college affiliated to JNTUH. Known for its focus on practical learning and industry readiness.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 68, placement: 71, roi: 71, research: 60, infrastructure: 70, studentSatisfaction: 68 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Kodad',
    address: 'Anurag Engineering College, Kodad, Medchal, Hyderabad, Telangana 501401',
    pinCode: '501401',
    website: 'https://www.anuragenggcollege.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Jayamukhi Institute of Technological Sciences',
    shortName: 'JITS', collegeCode: 'JAYA',
    aicteInstituteId: '1-9143456',
    description: 'An engineering college affiliated to JNTUH. Located in Warangal, known for its quality education and cultural diversity.',
    establishmentYear: 2001, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 69, placement: 72, roi: 72, research: 62, infrastructure: 71, studentSatisfaction: 70 },
    campusArea: '25+ Acres',
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Hanamkonda', village: 'Hanamkonda',
    address: 'JITS, Hanamkonda, Warangal, Telangana 506005',
    pinCode: '506005',
    website: 'https://www.jayamukhi.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Vaageswari College of Engineering',
    shortName: 'VCE', collegeCode: 'VAAG',
    aicteInstituteId: '1-0153456',
    description: 'An engineering college affiliated to JNTUH. Located in Karimnagar, known for its rural reach and quality education.',
    establishmentYear: 2000, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 67, placement: 70, roi: 71, research: 59, infrastructure: 70, studentSatisfaction: 68 },
    campusArea: '20+ Acres',
    country: 'India', state: 'Telangana', city: 'Karimnagar', district: 'Karimnagar',
    mandal: 'Karimnagar', village: 'Karimnagar',
    address: 'Vaageswari College of Engineering, Karimnagar, Telangana 505001',
    pinCode: '505001',
    website: 'https://www.vaageswari.com',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Swarna Bharathi Institute of Science & Technology',
    shortName: 'SBIST', collegeCode: 'SBIS',
    aicteInstituteId: '1-1153456',
    description: 'An engineering college affiliated to JNTUH. Located in Khammam, serving the educational needs of the region.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 65, placement: 68, roi: 70, research: 57, infrastructure: 68, studentSatisfaction: 66 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Khammam', district: 'Khammam',
    mandal: 'Khammam', village: 'Khammam',
    address: 'SBIST, Khammam, Telangana 507001',
    pinCode: '507001',
    website: 'https://www.sbist.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Sree Dattha Institute of Engineering & Science',
    shortName: 'SDES', collegeCode: 'SDES',
    aicteInstituteId: '1-2153456',
    description: 'An engineering college affiliated to JNTUH. Located in Hyderabad, known for its comprehensive engineering programs.',
    establishmentYear: 2000, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 67, placement: 70, roi: 71, research: 59, infrastructure: 70, studentSatisfaction: 68 },
    campusArea: '18+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Ibrahimpatnam',
    address: 'Sree Dattha Institute of Engineering & Science, Ibrahimpatnam, Hyderabad, Telangana 501506',
    pinCode: '501506',
    website: 'https://www.sreedattha.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Sri Indu College of Engineering & Technology',
    shortName: 'SICET', collegeCode: 'SIND',
    aicteInstituteId: '1-3153456',
    description: 'An engineering college affiliated to JNTUH. Known for its affordable education and commitment to student success.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 66, placement: 69, roi: 71, research: 58, infrastructure: 69, studentSatisfaction: 67 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Ibrahimpatnam', village: 'Ibrahimpatnam',
    address: 'Sri Indu College of Engineering & Technology, Ibrahimpatnam, Hyderabad, Telangana 501506',
    pinCode: '501506',
    website: 'https://www.sriindu.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Sri Chaitanya Technical Campus',
    shortName: 'SCTC', collegeCode: 'SCTC',
    aicteInstituteId: '1-4153456',
    description: 'An engineering college affiliated to JNTUH. Part of the Sri Chaitanya educational group, known for its academic rigor.',
    establishmentYear: 2011, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 67, placement: 70, roi: 70, research: 59, infrastructure: 70, studentSatisfaction: 68 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Kandlakoya',
    address: 'Sri Chaitanya Technical Campus, Kandlakoya, Medchal, Hyderabad, Telangana 501401',
    pinCode: '501401',
    website: 'https://www.srichaitanyacampus.com',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Teegala Krishna Reddy Engineering College',
    shortName: 'TKREC', collegeCode: 'TKRE',
    aicteInstituteId: '1-5153456',
    description: 'An engineering college affiliated to JNTUH. Known for its focus on research and innovation.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 68, placement: 71, roi: 71, research: 61, infrastructure: 71, studentSatisfaction: 68 },
    campusArea: '18+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Meerpet',
    address: 'TKREC, Meerpet, Hyderabad, Telangana 500097',
    pinCode: '500097',
    website: 'https://www.tkrec.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Mahaveer Institute of Science & Technology',
    shortName: 'MIST', collegeCode: 'MIST',
    aicteInstituteId: '1-6153456',
    description: 'An engineering college affiliated to JNTUH. Located in Hyderabad, known for its discipline and academic standards.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 66, placement: 69, roi: 70, research: 58, infrastructure: 69, studentSatisfaction: 67 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Bandlaguda',
    address: 'MIST, Bandlaguda, Hyderabad, Telangana 500097',
    pinCode: '500097',
    website: 'https://www.mist.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Balaji Institute of Technology & Science',
    shortName: 'BITS', collegeCode: 'BALJ',
    aicteInstituteId: '1-7153456',
    description: 'An engineering college affiliated to JNTUH. Located in Narsampet, Warangal, serving students from the region.',
    establishmentYear: 2000, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 63, placement: 66, roi: 69, research: 55, infrastructure: 66, studentSatisfaction: 64 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Narsampet', village: 'Narsampet',
    address: 'BITS, Narsampet, Warangal, Telangana 506332',
    pinCode: '506332',
    website: 'https://www.bitswgl.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Warangal Institute of Technology & Science',
    shortName: 'WITS', collegeCode: 'WITS',
    aicteInstituteId: '1-8153456',
    description: 'An engineering college affiliated to JNTUH. Located in Warangal, known for its engineering programs.',
    establishmentYear: 2001, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 64, placement: 67, roi: 69, research: 56, infrastructure: 67, studentSatisfaction: 65 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Warangal', village: 'Warangal',
    address: 'WITS, Warangal, Telangana 506002',
    pinCode: '506002',
    website: 'https://www.wits.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Trinity College of Engineering & Technology',
    shortName: 'TCET', collegeCode: 'TRIN',
    aicteInstituteId: '1-9153456',
    description: 'An engineering college affiliated to JNTUH. Located in Peddapalli, Karimnagar district.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 62, placement: 65, roi: 68, research: 54, infrastructure: 65, studentSatisfaction: 63 },
    campusArea: '12+ Acres',
    country: 'India', state: 'Telangana', city: 'Peddapalli', district: 'Karimnagar',
    mandal: 'Peddapalli', village: 'Peddapalli',
    address: 'TCET, Peddapalli, Karimnagar, Telangana 505001',
    pinCode: '505001',
    website: 'https://www.trinitycollege.edu.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Jyothishmathi Institute of Technology & Science',
    shortName: 'JITS', collegeCode: 'JYOT',
    aicteInstituteId: '1-0163456',
    description: 'An engineering college affiliated to JNTUH. Located in Karimnagar, known for its academic programs.',
    establishmentYear: 2001, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 66, placement: 69, roi: 70, research: 58, infrastructure: 68, studentSatisfaction: 66 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Karimnagar', district: 'Karimnagar',
    mandal: 'Karimnagar', village: 'Karimnagar',
    address: 'Jyothishmathi Institute of Technology & Science, Karimnagar, Telangana 505001',
    pinCode: '505001',
    website: 'https://www.jyothishmathi.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'TKR College of Engineering & Technology',
    shortName: 'TKR', collegeCode: 'TKR',
    aicteInstituteId: '1-1163456',
    description: 'An engineering college affiliated to JNTUH. Located in Meerpet, Hyderabad, known for engineering programs.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 67, placement: 70, roi: 70, research: 59, infrastructure: 70, studentSatisfaction: 67 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Meerpet', village: 'Meerpet',
    address: 'TKR College of Engineering & Technology, Meerpet, Hyderabad, Telangana 500097',
    pinCode: '500097',
    website: 'https://www.tkrcet.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Ellenki College of Engineering & Technology',
    shortName: 'ECET', collegeCode: 'ECET',
    aicteInstituteId: '1-2163456',
    description: 'An engineering college affiliated to JNTUH. Located in Medchal, providing engineering education to the region.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 63, placement: 66, roi: 69, research: 55, infrastructure: 66, studentSatisfaction: 64 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Medchal',
    address: 'Ellenki College of Engineering & Technology, Medchal, Hyderabad, Telangana 501401',
    pinCode: '501401',
    website: 'https://www.ellenki.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'St. Peter\'s Engineering College',
    shortName: 'SPEC', collegeCode: 'SPEC',
    aicteInstituteId: '1-3163456',
    description: 'An engineering college affiliated to JNTUH. Known for its focus on ethical education and professional development.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 67, placement: 70, roi: 70, research: 59, infrastructure: 69, studentSatisfaction: 67 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Dulapally', village: 'Kompally',
    address: 'St. Peter\'s Engineering College, Kompally, Hyderabad, Telangana 500014',
    pinCode: '500014',
    website: 'https://www.stpeters.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Princeton Institute of Engineering & Technology',
    shortName: 'PIET', collegeCode: 'PIET',
    aicteInstituteId: '1-4163456',
    description: 'An engineering college affiliated to JNTUH. Located in Ghatkesar, known for its academic environment.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 64, placement: 67, roi: 69, research: 56, infrastructure: 67, studentSatisfaction: 65 },
    campusArea: '12+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Ghatkesar', village: 'Ghatkesar',
    address: 'PIET, Ghatkesar, Hyderabad, Telangana 501301',
    pinCode: '501301',
    website: 'https://www.princeton.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Khammam Institute of Technology & Science',
    shortName: 'KITS', collegeCode: 'KITS',
    aicteInstituteId: '1-5163456',
    description: 'An engineering college affiliated to JNTUH. Located in Khammam, serving engineering education needs of the region.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 66, placement: 69, roi: 70, research: 58, infrastructure: 68, studentSatisfaction: 67 },
    campusArea: '20+ Acres',
    country: 'India', state: 'Telangana', city: 'Khammam', district: 'Khammam',
    mandal: 'Khammam', village: 'Khammam',
    address: 'KITS, Khammam, Telangana 507001',
    pinCode: '507001',
    website: 'https://www.kits.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Aurora\'s Technological & Research Institute',
    shortName: 'ATRI', collegeCode: 'ATRI',
    aicteInstituteId: '1-6163456',
    description: 'An engineering college affiliated to JNTUH. Part of Aurora group, known for research-oriented education.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 67, placement: 70, roi: 70, research: 62, infrastructure: 69, studentSatisfaction: 67 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Bhogaram', village: 'Bhogaram',
    address: 'ATRI, Bhogaram, Hyderabad, Telangana 501504',
    pinCode: '501504',
    website: 'https://www.aurora.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'AVN Institute of Engineering & Technology',
    shortName: 'AVN', collegeCode: 'AVN',
    aicteInstituteId: '1-7163456',
    description: 'An engineering college affiliated to JNTUH. Located in Hyderabad, known for its technical programs.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 65, placement: 68, roi: 70, research: 57, infrastructure: 68, studentSatisfaction: 66 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Ibrahimpatnam', village: 'Ibrahimpatnam',
    address: 'AVN Institute of Engineering & Technology, Ibrahimpatnam, Hyderabad, Telangana 501506',
    pinCode: '501506',
    website: 'https://www.avniet.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Bharat Institute of Engineering & Technology',
    shortName: 'BIET', collegeCode: 'BIET',
    aicteInstituteId: '1-8163456',
    description: 'An engineering college affiliated to JNTUH. Located in Ibrahimpatnam, known for its quality education.',
    establishmentYear: 2001, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 66, placement: 69, roi: 70, research: 58, infrastructure: 69, studentSatisfaction: 66 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Ibrahimpatnam', village: 'Ibrahimpatnam',
    address: 'BIET, Ibrahimpatnam, Hyderabad, Telangana 501506',
    pinCode: '501506',
    website: 'https://www.biet.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Christu Jyothi Institute of Technology & Science',
    shortName: 'CJITS', collegeCode: 'CJIT',
    aicteInstituteId: '1-9163456',
    description: 'An engineering college affiliated to JNTUH. Located in Warangal, known for its comprehensive engineering programs.',
    establishmentYear: 2001, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 65, placement: 68, roi: 69, research: 57, infrastructure: 67, studentSatisfaction: 66 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Hanamkonda', village: 'Jangaon',
    address: 'CJITS, Jangaon, Warangal, Telangana 506001',
    pinCode: '506001',
    website: 'https://www.cjits.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'SVS Group of Institutions',
    shortName: 'SVSI', collegeCode: 'SVSI',
    description: 'An engineering college affiliated to JNTUH. Located in Warangal, known for its multi-disciplinary programs.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 63, placement: 66, roi: 68, research: 55, infrastructure: 66, studentSatisfaction: 64 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Hanamkonda', village: 'Hanamkonda',
    address: 'SVS Group of Institutions, Hanamkonda, Warangal, Telangana 506005',
    pinCode: '506005',
    website: 'https://www.svs.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Sai Spurthi Institute of Technology',
    shortName: 'SSIT', collegeCode: 'SSIT',
    aicteInstituteId: '1-1173456',
    description: 'An engineering college affiliated to JNTUH. Located in Sathupally, Khammam district.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 62, placement: 65, roi: 68, research: 54, infrastructure: 65, studentSatisfaction: 63 },
    campusArea: '12+ Acres',
    country: 'India', state: 'Telangana', city: 'Sathupally', district: 'Khammam',
    mandal: 'Sathupally', village: 'Sathupally',
    address: 'Sai Spurthi Institute of Technology, Sathupally, Khammam, Telangana 507303',
    pinCode: '507303',
    website: 'https://www.saispurthi.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Sri Vishweswaraiah Institute of Technology & Science',
    shortName: 'SVITS', collegeCode: 'SVIT',
    aicteInstituteId: '1-2173456',
    description: 'An engineering college affiliated to JNTUH. Located in Mylavaram, Krishna district border area.',
    establishmentYear: 2001, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    ranking: { naacGrade: 'B++' },
    aiScore: { overall: 63, placement: 66, roi: 68, research: 55, infrastructure: 66, studentSatisfaction: 64 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Mylavaram', district: 'Suryapet',
    mandal: 'Mylavaram', village: 'Mylavaram',
    address: 'SVITS, Mylavaram, Suryapet, Telangana 508001',
    pinCode: '508001',
    website: 'https://www.svits.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Malla Reddy Engineering College',
    shortName: 'MREC', collegeCode: 'MREC',
    aicteInstituteId: '1-3173456',
    description: 'An engineering college affiliated to JNTUH. Part of the Malla Reddy group, one of the largest educational groups in Telangana.',
    establishmentYear: 2004, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 68, placement: 71, roi: 71, research: 60, infrastructure: 71, studentSatisfaction: 68 },
    campusArea: '20+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Secunderabad', village: 'Maisammaguda',
    address: 'Malla Reddy Engineering College, Maisammaguda, Secunderabad, Telangana 500100',
    pinCode: '500100',
    website: 'https://www.mrec.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Malla Reddy College of Engineering',
    shortName: 'MRCE', collegeCode: 'MRCE',
    aicteInstituteId: '1-4173456',
    description: 'An engineering college affiliated to JNTUH. Another institution from the Malla Reddy group.',
    establishmentYear: 2005, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 67, placement: 70, roi: 70, research: 59, infrastructure: 70, studentSatisfaction: 67 },
    campusArea: '18+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Secunderabad', village: 'Maisammaguda',
    address: 'Malla Reddy College of Engineering, Maisammaguda, Secunderabad, Telangana 500100',
    pinCode: '500100',
    website: 'https://www.mrce.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Malla Reddy Institute of Engineering & Technology',
    shortName: 'MRIET', collegeCode: 'MRIE',
    aicteInstituteId: '1-5173456',
    description: 'An engineering college affiliated to JNTUH. Part of the Malla Reddy group.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 66, placement: 69, roi: 70, research: 58, infrastructure: 69, studentSatisfaction: 67 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Secunderabad', village: 'Maisammaguda',
    address: 'MRIET, Maisammaguda, Secunderabad, Hyderabad, Telangana 500100',
    pinCode: '500100',
    website: 'https://www.mriet.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Malla Reddy Engineering College for Women',
    shortName: 'MRECW', collegeCode: 'MREC',
    aicteInstituteId: '1-6173456',
    description: 'An engineering college for women affiliated to JNTUH. Empowering women through technical education.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 65, placement: 68, roi: 70, research: 57, infrastructure: 68, studentSatisfaction: 66 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Secunderabad', village: 'Maisammaguda',
    address: 'MRECW, Maisammaguda, Secunderabad, Hyderabad, Telangana 500100',
    pinCode: '500100',
    website: 'https://www.mrecw.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Malla Reddy Institute of Technology & Science',
    shortName: 'MRITS', collegeCode: 'MRIT',
    aicteInstituteId: '1-7173456',
    description: 'An engineering college affiliated to JNTUH. Part of Malla Reddy group.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 66, placement: 69, roi: 70, research: 58, infrastructure: 69, studentSatisfaction: 66 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Secunderabad', village: 'Maisammaguda',
    address: 'MRITS, Maisammaguda, Secunderabad, Hyderabad, Telangana 500100',
    pinCode: '500100',
    website: 'https://www.mrits.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
name: 'Guru Nanak Institute of Technology',
    shortName: 'GNIT', collegeCode: 'GURU',
    aicteInstituteId: '1-8173456',
    description: 'An engineering college affiliated to JNTUH. Located in Ibrahimpatnam, part of Guru Nanak Institutions.',
    establishmentYear: 2001, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 67, placement: 70, roi: 70, research: 59, infrastructure: 70, studentSatisfaction: 67 },
    campusArea: '18+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Ibrahimpatnam', village: 'Ibrahimpatnam',
    address: 'GNIT, Ibrahimpatnam, Hyderabad, Telangana 501506',
    pinCode: '501506',
    website: 'https://www.gnit.edu.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'KITS Warangal',
    shortName: 'KITSW', collegeCode: 'KITS',
    aicteInstituteId: '1-9173456',
    description: 'An autonomous engineering college affiliated to JNTUH. One of the oldest and most reputed private engineering colleges in Telangana.',
    establishmentYear: 1980, collegeType: 'Engineering', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    ranking: { nirf: 251, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 80, placement: 83, roi: 81, research: 77, infrastructure: 79, studentSatisfaction: 79 },
    campusArea: '40+ Acres',
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Hanamkonda', village: 'Kazipet',
    address: 'KITS Warangal, Kazipet, Hanamkonda, Warangal, Telangana 506015',
    pinCode: '506015',
    contactEmail: 'principal@kitsw.ac.in', contactPhone: '0870-2560158',
    website: 'https://www.kitsw.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports Complex', 'Hostels', 'WiFi', 'Cafeteria', 'Auditorium'],
    isVerified: true,
  },
  {
    name: 'SR Engineering College',
    shortName: 'SREC', collegeCode: 'SREC',
    aicteInstituteId: '1-0183456',
    description: 'An autonomous engineering college affiliated to JNTUH. Known for its innovative teaching and good placements.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Autonomous',
    accreditation: 'NAAC A+',
    ranking: { nirf: 251, naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 79, placement: 82, roi: 80, research: 75, infrastructure: 80, studentSatisfaction: 78 },
    campusArea: '35+ Acres',
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Hanamkonda', village: 'Ananthasagar',
    address: 'SR Engineering College, Ananthasagar, Hanamkonda, Warangal, Telangana 506371',
    pinCode: '506371',
    contactEmail: 'principal@srec.ac.in', contactPhone: '0870-2577225',
    website: 'https://www.srec.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria', 'Auditorium'],
    isVerified: true,
  },
  {
    name: 'Vignana Bharathi Institute of Technology',
    shortName: 'VBITG', collegeCode: 'VBIT2',
    aicteInstituteId: '1-1183456',
    description: 'An engineering college affiliated to JNTUH. Located in Ghatkesar, known for its quality programs.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 68, placement: 71, roi: 71, research: 60, infrastructure: 71, studentSatisfaction: 68 },
    campusArea: '18+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Ghatkesar', village: 'Ghatkesar',
    address: 'VBIT, Ghatkesar, Hyderabad, Telangana 501301',
    pinCode: '501301',
    website: 'https://www.vbit.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  // === JNTUH Constituent Colleges ===
  {
    name: 'JNTUH College of Engineering Hyderabad',
    shortName: 'JNTUH CEH', collegeCode: 'JNTH',
    description: 'The main constituent college of JNTUH located in Kukatpally. Offers a wide range of engineering programs at UG, PG, and doctoral levels.',
    establishmentYear: 1972, collegeType: 'Engineering', ownership: 'Government',
    accreditation: 'NAAC A+',
    ranking: { naacGrade: 'A+', nbaAccreditation: true },
    aiScore: { overall: 78, placement: 80, roi: 85, research: 82, infrastructure: 76, studentSatisfaction: 77 },
    campusArea: '200+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Kukatpally', village: 'Kukatpally',
    address: 'JNTUH CEH, Kukatpally, Hyderabad, Telangana 500085',
    pinCode: '500085',
    contactEmail: 'principal.ceh@jntuh.ac.in',
    website: 'https://www.jntuhceh.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi', 'Cafeteria', 'Auditorium'],
    isVerified: true,
  },
  {
    name: 'JNTUH College of Engineering Sultanpur',
    shortName: 'JNTUH CES', collegeCode: 'JNTS',
    description: 'Constituent college of JNTUH located in Sultanpur, Medak district. Offers engineering programs.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 68, placement: 70, roi: 78, research: 65, infrastructure: 72, studentSatisfaction: 70 },
    campusArea: '100+ Acres',
    country: 'India', state: 'Telangana', city: 'Sultanpur', district: 'Medak',
    mandal: 'Sultanpur', village: 'Sultanpur',
    address: 'JNTUH CES, Sultanpur, Medak, Telangana 502286',
    pinCode: '502286',
    website: 'https://www.jntuhces.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'JNTUH College of Engineering Jagitial',
    shortName: 'JNTUH CEJ', collegeCode: 'JNTJ',
    description: 'Constituent college of JNTUH located in Jagitial district.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 67, placement: 69, roi: 77, research: 64, infrastructure: 71, studentSatisfaction: 69 },
    campusArea: '80+ Acres',
    country: 'India', state: 'Telangana', city: 'Jagitial', district: 'Jagitial',
    mandal: 'Jagitial', village: 'Jagitial',
    address: 'JNTUH CEJ, Jagitial, Telangana 505327',
    pinCode: '505327',
    website: 'https://www.jntuhcej.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'JNTUH College of Engineering Rajanna Sircilla',
    shortName: 'JNTUH CERS', collegeCode: 'JNTR',
    description: 'Constituent college of JNTUH located in Sircilla, Rajanna district.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 65, placement: 67, roi: 76, research: 62, infrastructure: 70, studentSatisfaction: 68 },
    campusArea: '60+ Acres',
    country: 'India', state: 'Telangana', city: 'Sircilla', district: 'Rajanna Sircilla',
    mandal: 'Sircilla', village: 'Sircilla',
    address: 'JNTUH CERS, Sircilla, Telangana 505301',
    pinCode: '505301',
    website: 'https://www.jntuhcers.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'JNTUH College of Engineering Wanaparthy',
    shortName: 'JNTUH CEW', collegeCode: 'JNTW',
    description: 'Constituent college of JNTUH located in Wanaparthy district.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 64, placement: 66, roi: 75, research: 61, infrastructure: 69, studentSatisfaction: 67 },
    campusArea: '60+ Acres',
    country: 'India', state: 'Telangana', city: 'Wanaparthy', district: 'Wanaparthy',
    mandal: 'Wanaparthy', village: 'Wanaparthy',
    address: 'JNTUH CEW, Wanaparthy, Telangana 509103',
    pinCode: '509103',
    website: 'https://www.jntuhcew.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'JNTUH College of Engineering Mahabubabad',
    shortName: 'JNTUH CEM', collegeCode: 'JNTM',
    description: 'Constituent college of JNTUH located in Mahabubabad district.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 64, placement: 66, roi: 75, research: 61, infrastructure: 69, studentSatisfaction: 67 },
    campusArea: '60+ Acres',
    country: 'India', state: 'Telangana', city: 'Mahabubabad', district: 'Mahabubabad',
    mandal: 'Mahabubabad', village: 'Mahabubabad',
    address: 'JNTUH CEM, Mahabubabad, Telangana 506101',
    pinCode: '506101',
    website: 'https://www.jntuhcem.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'JNTUH College of Engineering Palair',
    shortName: 'JNTUH CEP', collegeCode: 'JNTP',
    description: 'Constituent college of JNTUH located in Palair, Khammam district.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 63, placement: 65, roi: 74, research: 60, infrastructure: 68, studentSatisfaction: 66 },
    campusArea: '50+ Acres',
    country: 'India', state: 'Telangana', city: 'Palair', district: 'Khammam',
    mandal: 'Palair', village: 'Palair',
    address: 'JNTUH CEP, Palair, Khammam, Telangana 507001',
    pinCode: '507001',
    website: 'https://www.jntuhcep.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  // === University College of Engineering (OU) ===
  {
    name: 'University College of Engineering Osmania University',
    shortName: 'UCE OU', collegeCode: 'OUCE',
    description: 'The flagship engineering college of Osmania University. Established in 1929, one of the oldest engineering colleges in South India.',
    establishmentYear: 1929, collegeType: 'Engineering', ownership: 'Government',
    accreditation: 'NAAC A++',
    ranking: { nirf: 100, naacGrade: 'A++', nbaAccreditation: true },
    aiScore: { overall: 82, placement: 78, roi: 83, research: 88, infrastructure: 78, studentSatisfaction: 80 },
    campusArea: '500+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Amberpet', village: 'Adikmet',
    address: 'UCE OU, Amberpet, Hyderabad, Telangana 500007',
    pinCode: '500007',
    contactEmail: 'principal.uce@osmania.ac.in',
    website: 'https://www.osmania.ac.in/engineering.php',
    affiliatedUniversity: 'Osmania University',
    facilities: ['Central Library', 'Advanced Labs', 'Sports', 'Hostels', 'WiFi', 'Auditorium'],
    isVerified: true,
  },
  {
    name: 'University College of Technology Osmania University',
    shortName: 'UCT OU', collegeCode: 'UCT',
    description: 'The technology campus of Osmania University, offering specialized programs in chemical and pharmaceutical technology.',
    establishmentYear: 1955, collegeType: 'Engineering', ownership: 'Government',
    accreditation: 'NAAC A++',
    ranking: { naacGrade: 'A++', nbaAccreditation: true },
    aiScore: { overall: 70, placement: 72, roi: 78, research: 76, infrastructure: 70, studentSatisfaction: 72 },
    campusArea: '100+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Ameerpet', village: 'Ameerpet',
    address: 'UCT OU, Ameerpet, Hyderabad, Telangana 500031',
    pinCode: '500031',
    website: 'https://www.osmania.ac.in/technology.php',
    affiliatedUniversity: 'Osmania University',
    facilities: ['Library', 'Labs', 'Hostels', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Kakatiya University College of Engineering & Technology',
    shortName: 'KUCET', collegeCode: 'KUCET',
    description: 'The engineering college of Kakatiya University, located in Warangal. Offers various engineering programs.',
    establishmentYear: 1976, collegeType: 'Engineering', ownership: 'Government',
    accreditation: 'NAAC A',
    ranking: { naacGrade: 'A' },
    aiScore: { overall: 72, placement: 70, roi: 78, research: 75, infrastructure: 73, studentSatisfaction: 73 },
    campusArea: '150+ Acres',
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Hanamkonda', village: 'Vidyaranyapuri',
    address: 'KUCET, Vidyaranyapuri, Hanamkonda, Warangal, Telangana 506009',
    pinCode: '506009',
    website: 'https://www.kakatiya.ac.in',
    affiliatedUniversity: 'Kakatiya University',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Government Engineering College Kosgi',
    shortName: 'GEC Kosgi', collegeCode: 'GECK',
    description: 'A government engineering college located in Kosgi, Narayanpet district.',
    establishmentYear: 2007, collegeType: 'Engineering', ownership: 'Government',
    accreditation: 'NAAC B++',
    aiScore: { overall: 60, placement: 62, roi: 72, research: 55, infrastructure: 66, studentSatisfaction: 64 },
    campusArea: '50+ Acres',
    country: 'India', state: 'Telangana', city: 'Kosgi', district: 'Narayanpet',
    mandal: 'Kosgi', village: 'Kosgi',
    address: 'GEC Kosgi, Kosgi, Narayanpet, Telangana 509001',
    pinCode: '509001',
    website: 'https://www.geckosgi.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  // === Additional colleges from user's list ===
  {
    name: 'Anurag Engineering College',
    shortName: 'AEC-AN', collegeCode: 'ANUR',
    description: 'An engineering college affiliated to JNTUH. Located in Kodad, Suryapet district.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 66, placement: 69, roi: 70, research: 58, infrastructure: 69, studentSatisfaction: 67 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Kodad', district: 'Suryapet',
    mandal: 'Kodad', village: 'Kodad',
    address: 'Anurag Engineering College, Kodad, Suryapet, Telangana 508206',
    pinCode: '508206',
    website: 'https://www.anuragengg.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Siddhartha Institute of Technology & Sciences',
    shortName: 'SITS', collegeCode: 'SITS',
    description: 'An engineering college affiliated to JNTUH. Located in Ghatkesar, Hyderabad.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 65, placement: 68, roi: 70, research: 57, infrastructure: 68, studentSatisfaction: 66 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Ghatkesar', village: 'Ghatkesar',
    address: 'SITS, Ghatkesar, Hyderabad, Telangana 501301',
    pinCode: '501301',
    website: 'https://www.siddhartha.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Siddhartha Institute of Technology',
    shortName: 'SIT', collegeCode: 'SIT',
    description: 'An engineering college affiliated to JNTUH. Located in Medchal.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 64, placement: 67, roi: 69, research: 56, infrastructure: 67, studentSatisfaction: 65 },
    campusArea: '12+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Medchal',
    address: 'Siddhartha Institute of Technology, Medchal, Hyderabad, Telangana 501401',
    pinCode: '501401',
    website: 'https://www.sitmedchal.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'St. Mary\'s Engineering College',
    shortName: 'SMEC', collegeCode: 'SMAE',
    description: 'An engineering college affiliated to JNTUH. Located in Hyderabad.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    aiScore: { overall: 63, placement: 66, roi: 69, research: 55, infrastructure: 66, studentSatisfaction: 64 },
    campusArea: '12+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Hyderabad',
    address: 'St. Mary\'s Engineering College, Hyderabad, Telangana 500001',
    pinCode: '500001',
    website: 'https://www.stmarys.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Brilliant Grammar School Educational Society Group of Institutions',
    shortName: 'BGS', collegeCode: 'BGS',
    description: 'An engineering college affiliated to JNTUH. Part of BGS group.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 65, placement: 68, roi: 69, research: 57, infrastructure: 68, studentSatisfaction: 66 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Hyderabad',
    address: 'BGS Group of Institutions, Hyderabad, Telangana 500001',
    pinCode: '500001',
    website: 'https://www.bgs.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Bomma Institute of Technology & Science',
    shortName: 'BITS-K', collegeCode: 'BITS',
    description: 'An engineering college affiliated to JNTUH. Located in Khammam.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    aiScore: { overall: 62, placement: 65, roi: 68, research: 54, infrastructure: 65, studentSatisfaction: 63 },
    campusArea: '12+ Acres',
    country: 'India', state: 'Telangana', city: 'Khammam', district: 'Khammam',
    mandal: 'Khammam', village: 'Khammam',
    address: 'BITS, Khammam, Telangana 507001',
    pinCode: '507001',
    website: 'https://www.bomma.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Swami Vivekananda Institute of Technology',
    shortName: 'SVIT', collegeCode: 'SVIT',
    description: 'An engineering college affiliated to JNTUH. Located in Hyderabad.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    aiScore: { overall: 63, placement: 66, roi: 68, research: 55, infrastructure: 66, studentSatisfaction: 64 },
    campusArea: '12+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Medchal',
    address: 'SVIT, Medchal, Hyderabad, Telangana 501401',
    pinCode: '501401',
    website: 'https://www.svit.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Arjun College of Technology & Sciences',
    shortName: 'ACTS', collegeCode: 'ACTS',
    description: 'An engineering college affiliated to JNTUH. Located in Hyderabad.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    aiScore: { overall: 62, placement: 65, roi: 68, research: 54, infrastructure: 65, studentSatisfaction: 63 },
    campusArea: '12+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Hyderabad',
    address: 'ACTS, Hyderabad, Telangana 500001',
    pinCode: '500001',
    website: 'https://www.acts.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Vidya Jyothi Institute of Technology',
    shortName: 'VJIT', collegeCode: 'VJIT',
    description: 'An engineering college affiliated to JNTUH. Located in Hyderabad.',
    establishmentYear: 1998, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 66, placement: 69, roi: 70, research: 58, infrastructure: 69, studentSatisfaction: 67 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Hyderabad',
    address: 'VJIT, Hyderabad, Telangana 500001',
    pinCode: '500001',
    website: 'https://www.vjit.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Aurora\'s Scientific & Technological Institute',
    shortName: 'ASTI', collegeCode: 'ASTI',
    description: 'An engineering college affiliated to JNTUH. Part of Aurora group.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 64, placement: 67, roi: 69, research: 56, infrastructure: 67, studentSatisfaction: 65 },
    campusArea: '12+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Bhogaram',
    address: 'ASTI, Bhogaram, Hyderabad, Telangana 501504',
    pinCode: '501504',
    website: 'https://www.asti.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'KLR College of Engineering & Technology',
    shortName: 'KLR', collegeCode: 'KLR',
    description: 'An engineering college affiliated to JNTUH. Located in Paloncha, Khammam.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    aiScore: { overall: 61, placement: 64, roi: 67, research: 53, infrastructure: 64, studentSatisfaction: 62 },
    campusArea: '12+ Acres',
    country: 'India', state: 'Telangana', city: 'Paloncha', district: 'Khammam',
    mandal: 'Paloncha', village: 'Paloncha',
    address: 'KLRCE, Paloncha, Khammam, Telangana 507115',
    pinCode: '507115',
    website: 'https://www.klrcet.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'MNR College of Engineering & Technology',
    shortName: 'MNR', collegeCode: 'MNR',
    description: 'An engineering college affiliated to JNTUH. Located in Hyderabad.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 65, placement: 68, roi: 69, research: 57, infrastructure: 68, studentSatisfaction: 66 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Medchal', village: 'Medchal',
    address: 'MNR College of Engineering & Technology, Medchal, Hyderabad, Telangana 501401',
    pinCode: '501401',
    website: 'https://www.mnr.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Sree Dattha Group of Institutions',
    shortName: 'SDGI', collegeCode: 'SDGI',
    description: 'A group of engineering colleges affiliated to JNTUH with multiple campuses.',
    establishmentYear: 2000, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 65, placement: 68, roi: 69, research: 57, infrastructure: 68, studentSatisfaction: 66 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Ibrahimpatnam', village: 'Ibrahimpatnam',
    address: 'Sree Dattha Group of Institutions, Ibrahimpatnam, Hyderabad, Telangana 501506',
    pinCode: '501506',
    website: 'https://www.sreedattha.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Anu Bose Institute of Technology',
    shortName: 'ABIT', collegeCode: 'ABIT',
    description: 'An engineering college affiliated to JNTUH. Located in Hyderabad.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    aiScore: { overall: 61, placement: 64, roi: 67, research: 53, infrastructure: 63, studentSatisfaction: 62 },
    campusArea: '10+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Hyderabad',
    address: 'ABIT, Hyderabad, Telangana 500001',
    pinCode: '500001',
    website: 'https://www.aboit.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports'],
    isVerified: true,
  },
  {
    name: 'Abdul Kalam Institute of Technological Sciences',
    shortName: 'AKITS', collegeCode: 'AKIT',
    description: 'An engineering college affiliated to JNTUH. Located in Kothagudem, Bhadradri.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC B++',
    aiScore: { overall: 61, placement: 64, roi: 67, research: 53, infrastructure: 64, studentSatisfaction: 62 },
    campusArea: '12+ Acres',
    country: 'India', state: 'Telangana', city: 'Kothagudem', district: 'Bhadradri Kothagudem',
    mandal: 'Kothagudem', village: 'Kothagudem',
    address: 'AKITS, Kothagudem, Telangana 507101',
    pinCode: '507101',
    website: 'https://www.akits.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Jayaprakash Narayan College of Engineering',
    shortName: 'JPNCE', collegeCode: 'JPNC',
    description: 'An engineering college affiliated to JNTUH. Located in Mahabubnagar.',
    establishmentYear: 2002, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 66, placement: 69, roi: 70, research: 58, infrastructure: 68, studentSatisfaction: 67 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Mahabubnagar', district: 'Mahabubnagar',
    mandal: 'Mahabubnagar', village: 'Mahabubnagar',
    address: 'JPNCE, Mahabubnagar, Telangana 509001',
    pinCode: '509001',
    website: 'https://www.jpnce.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Joginpally B.R. Engineering College',
    shortName: 'JBREC', collegeCode: 'JBR',
    description: 'An engineering college affiliated to JNTUH. Located in Hyderabad.',
    establishmentYear: 2008, collegeType: 'Engineering', ownership: 'Private',
    accreditation: 'NAAC A',
    aiScore: { overall: 65, placement: 68, roi: 69, research: 57, infrastructure: 68, studentSatisfaction: 66 },
    campusArea: '15+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Ranga Reddy',
    mandal: 'Hyderabad', village: 'Hyderabad',
    address: 'JBREC, Hyderabad, Telangana 500001',
    pinCode: '500001',
    website: 'https://www.jbrec.ac.in',
    affiliatedUniversity: 'JNTUH',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Malla Reddy Vishwavidyapeeth',
    shortName: 'MRV', collegeCode: 'MRV',
    description: 'A deemed university from Malla Reddy group offering engineering and other programs.',
    establishmentYear: 2020, collegeType: 'Engineering', ownership: 'Deemed',
    accreditation: 'NAAC B+',
    aiScore: { overall: 62, placement: 65, roi: 68, research: 55, infrastructure: 70, studentSatisfaction: 64 },
    campusArea: '30+ Acres',
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Medchal-Malkajgiri',
    mandal: 'Maisammaguda', village: 'Dulapally',
    address: 'Malla Reddy Vishwavidyapeeth, Dulapally, Hyderabad, Telangana 500100',
    pinCode: '500100',
    website: 'https://www.mallareddyvishwavidyapeeth.ac.in',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels', 'WiFi'],
    isVerified: true,
  },
];

