export const telanganaPolytechnicColleges = [
  {
    name: 'Government Polytechnic Hyderabad',
    shortName: 'GPH', collegeCode: 'GPH',
    description: 'One of the oldest government polytechnics in Telangana, offering diploma programs in various engineering disciplines.',
    establishmentYear: 1960, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 70, placement: 68, roi: 76, research: 55, infrastructure: 72, studentSatisfaction: 70 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Hyderabad', village: 'Hyderabad',
    address: 'Government Polytechnic Hyderabad, Hyderabad, Telangana 500001',
    pinCode: '500001',
    website: 'https://www.gpthyderabad.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs', 'Sports', 'WiFi', 'Cafeteria'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Masab Tank',
    shortName: 'GPMT', collegeCode: 'GPMT',
    description: 'Government polytechnic located in Masab Tank, Hyderabad, offering diploma programs.',
    establishmentYear: 1970, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 68, placement: 66, roi: 75, research: 53, infrastructure: 70, studentSatisfaction: 69 },
    country: 'India', state: 'Telangana', city: 'Hyderabad', district: 'Hyderabad',
    mandal: 'Masab Tank', village: 'Masab Tank',
    address: 'Government Polytechnic, Masab Tank, Hyderabad, Telangana 500028',
    pinCode: '500028',
    website: 'https://www.gpmasabtank.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs', 'Sports', 'WiFi'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Warangal',
    shortName: 'GPW', collegeCode: 'GPW',
    description: 'Government polytechnic located in Warangal offering diploma programs.',
    establishmentYear: 1960, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 67, placement: 65, roi: 74, research: 52, infrastructure: 69, studentSatisfaction: 68 },
    country: 'India', state: 'Telangana', city: 'Warangal', district: 'Warangal Urban',
    mandal: 'Warangal', village: 'Warangal',
    address: 'Government Polytechnic, Warangal, Telangana 506002',
    pinCode: '506002',
    website: 'https://www.gpwarangal.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Nizamabad',
    shortName: 'GPN', collegeCode: 'GPN',
    description: 'Government polytechnic offering diploma programs in Nizamabad.',
    establishmentYear: 1970, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 66, placement: 64, roi: 73, research: 51, infrastructure: 68, studentSatisfaction: 67 },
    country: 'India', state: 'Telangana', city: 'Nizamabad', district: 'Nizamabad',
    mandal: 'Nizamabad', village: 'Nizamabad',
    address: 'Government Polytechnic, Nizamabad, Telangana 503001',
    pinCode: '503001',
    website: 'https://www.gpnizamabad.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Karimnagar',
    shortName: 'GPK', collegeCode: 'GPK',
    description: 'Government polytechnic located in Karimnagar offering various diploma programs.',
    establishmentYear: 1970, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 66, placement: 64, roi: 73, research: 51, infrastructure: 68, studentSatisfaction: 67 },
    country: 'India', state: 'Telangana', city: 'Karimnagar', district: 'Karimnagar',
    mandal: 'Karimnagar', village: 'Karimnagar',
    address: 'Government Polytechnic, Karimnagar, Telangana 505001',
    pinCode: '505001',
    website: 'https://www.gpkarimnagar.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs', 'Sports', 'Hostels'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Mahabubnagar',
    shortName: 'GPM', collegeCode: 'GPM',
    description: 'Government polytechnic in Mahabubnagar offering diploma programs.',
    establishmentYear: 1980, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 65, placement: 63, roi: 72, research: 50, infrastructure: 67, studentSatisfaction: 66 },
    country: 'India', state: 'Telangana', city: 'Mahabubnagar', district: 'Mahabubnagar',
    mandal: 'Mahabubnagar', village: 'Mahabubnagar',
    address: 'Government Polytechnic, Mahabubnagar, Telangana 509001',
    pinCode: '509001',
    website: 'https://www.gpmahabubnagar.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs', 'Sports'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Khammam',
    shortName: 'GPKH', collegeCode: 'GPKH',
    description: 'Government polytechnic in Khammam offering diploma programs.',
    establishmentYear: 1980, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 65, placement: 63, roi: 72, research: 50, infrastructure: 67, studentSatisfaction: 66 },
    country: 'India', state: 'Telangana', city: 'Khammam', district: 'Khammam',
    mandal: 'Khammam', village: 'Khammam',
    address: 'Government Polytechnic, Khammam, Telangana 507001',
    pinCode: '507001',
    website: 'https://www.gpkhammam.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs', 'Sports'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Nalgonda',
    shortName: 'GPNG', collegeCode: 'GPNG',
    description: 'Government polytechnic in Nalgonda offering diploma programs.',
    establishmentYear: 1980, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 65, placement: 63, roi: 72, research: 50, infrastructure: 67, studentSatisfaction: 66 },
    country: 'India', state: 'Telangana', city: 'Nalgonda', district: 'Nalgonda',
    mandal: 'Nalgonda', village: 'Nalgonda',
    address: 'Government Polytechnic, Nalgonda, Telangana 508001',
    pinCode: '508001',
    website: 'https://www.gpnalgonda.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs', 'Sports'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Adilabad',
    shortName: 'GPA', collegeCode: 'GPA',
    description: 'Government polytechnic in Adilabad offering diploma programs.',
    establishmentYear: 1980, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC A',
    aiScore: { overall: 64, placement: 62, roi: 71, research: 49, infrastructure: 66, studentSatisfaction: 65 },
    country: 'India', state: 'Telangana', city: 'Adilabad', district: 'Adilabad',
    mandal: 'Adilabad', village: 'Adilabad',
    address: 'Government Polytechnic, Adilabad, Telangana 504001',
    pinCode: '504001',
    website: 'https://www.gpadilabad.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs', 'Sports'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Siddipet',
    shortName: 'GPS', collegeCode: 'GPS',
    description: 'Government polytechnic in Siddipet offering diploma programs.',
    establishmentYear: 2008, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC B++',
    aiScore: { overall: 62, placement: 60, roi: 70, research: 48, infrastructure: 65, studentSatisfaction: 64 },
    country: 'India', state: 'Telangana', city: 'Siddipet', district: 'Siddipet',
    mandal: 'Siddipet', village: 'Siddipet',
    address: 'Government Polytechnic, Siddipet, Telangana 502103',
    pinCode: '502103',
    website: 'https://www.gpsiddipet.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Sircilla',
    shortName: 'GPSR', collegeCode: 'GPSR',
    description: 'Government polytechnic in Sircilla offering diploma programs.',
    establishmentYear: 2008, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC B++',
    aiScore: { overall: 61, placement: 59, roi: 69, research: 47, infrastructure: 64, studentSatisfaction: 63 },
    country: 'India', state: 'Telangana', city: 'Sircilla', district: 'Rajanna Sircilla',
    mandal: 'Sircilla', village: 'Sircilla',
    address: 'Government Polytechnic, Sircilla, Telangana 505301',
    pinCode: '505301',
    website: 'https://www.gpsircilla.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Medak',
    shortName: 'GPMK', collegeCode: 'GPMK',
    description: 'Government polytechnic in Medak offering diploma programs.',
    establishmentYear: 2008, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC B++',
    aiScore: { overall: 61, placement: 59, roi: 69, research: 47, infrastructure: 64, studentSatisfaction: 63 },
    country: 'India', state: 'Telangana', city: 'Medak', district: 'Medak',
    mandal: 'Medak', village: 'Medak',
    address: 'Government Polytechnic, Medak, Telangana 502110',
    pinCode: '502110',
    website: 'https://www.gpmedak.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Sangareddy',
    shortName: 'GPSG', collegeCode: 'GPSG',
    description: 'Government polytechnic in Sangareddy offering diploma programs.',
    establishmentYear: 2008, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC B++',
    aiScore: { overall: 62, placement: 60, roi: 70, research: 48, infrastructure: 65, studentSatisfaction: 64 },
    country: 'India', state: 'Telangana', city: 'Sangareddy', district: 'Sangareddy',
    mandal: 'Sangareddy', village: 'Sangareddy',
    address: 'Government Polytechnic, Sangareddy, Telangana 502001',
    pinCode: '502001',
    website: 'https://www.gpsangareddy.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Wanaparthy',
    shortName: 'GPWP', collegeCode: 'GPWP',
    description: 'Government polytechnic in Wanaparthy offering diploma programs.',
    establishmentYear: 2008, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC B++',
    aiScore: { overall: 61, placement: 59, roi: 69, research: 47, infrastructure: 64, studentSatisfaction: 63 },
    country: 'India', state: 'Telangana', city: 'Wanaparthy', district: 'Wanaparthy',
    mandal: 'Wanaparthy', village: 'Wanaparthy',
    address: 'Government Polytechnic, Wanaparthy, Telangana 509103',
    pinCode: '509103',
    website: 'https://www.gpwanaparthy.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Mahabubabad',
    shortName: 'GPMB', collegeCode: 'GPMB',
    description: 'Government polytechnic in Mahabubabad offering diploma programs.',
    establishmentYear: 2008, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC B++',
    aiScore: { overall: 61, placement: 59, roi: 69, research: 47, infrastructure: 64, studentSatisfaction: 63 },
    country: 'India', state: 'Telangana', city: 'Mahabubabad', district: 'Mahabubabad',
    mandal: 'Mahabubabad', village: 'Mahabubabad',
    address: 'Government Polytechnic, Mahabubabad, Telangana 506101',
    pinCode: '506101',
    website: 'https://www.gpmahabubabad.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs'],
    isVerified: true,
  },
  {
    name: 'Government Polytechnic Kothagudem',
    shortName: 'GPKG', collegeCode: 'GPKG',
    description: 'Government polytechnic in Kothagudem offering diploma programs.',
    establishmentYear: 2008, collegeType: 'Polytechnic', ownership: 'Government',
    accreditation: 'NAAC B++',
    aiScore: { overall: 62, placement: 60, roi: 70, research: 48, infrastructure: 65, studentSatisfaction: 64 },
    country: 'India', state: 'Telangana', city: 'Kothagudem', district: 'Bhadradri Kothagudem',
    mandal: 'Kothagudem', village: 'Kothagudem',
    address: 'Government Polytechnic, Kothagudem, Telangana 507101',
    pinCode: '507101',
    website: 'https://www.gpkothagudem.ac.in',
    affiliatedUniversity: 'State Board of Technical Education',
    facilities: ['Library', 'Labs'],
    isVerified: true,
  },
];

